class Datak {
  static List<Map<String, List<String>>> data = [
    {
      'basaLoma': ['Abus'],
      'basaLemesSorangan': ['lebet'],
      'basaLemesBatur': ['lebet'],
      'bahasaIndonesia': ['masuk kedalam'],
    },
    {
      'basaLoma': ['acan'],
      'basaLemesSorangan': ['teu acan'],
      'basaLemesBatur': ['teu acan'],
      'bahasaIndonesia': ['belum'],
    },
    {
      'basaLoma': ['adi'],
      'basaLemesSorangan': ['(pun)adi'],
      'basaLemesBatur': ['(tuang)rai,(tuang)rayi'],
      'bahasaIndonesia': ['adik'],
    },
    {
      'basaLoma': ['adi beuteung'],
      'basaLemesSorangan': ['(pun)adi'],
      'basaLemesBatur': ['(tuang)rai,(tuang)rayi'],
      'bahasaIndonesia': ['adik ipar'],
    },
    {
      'basaLoma': ['adu'],
      'basaLemesSorangan': ['aben'],
      'basaLemesBatur': ['aben'],
      'bahasaIndonesia': ['adu'],
    },
    {
      'basaLoma': ['ais'],
      'basaLemesSorangan': ['ais'],
      'basaLemesBatur': ['emban'],
      'bahasaIndonesia': ['menggendong'],
    },
    {
      'basaLoma': ['ajang'],
      'basaLemesSorangan': ['kanggo'],
      'basaLemesBatur': ['haturan,kanggo'],
      'bahasaIndonesia': ['untuk'],
    },
    {
      'basaLoma': ['ajar'],
      'basaLemesSorangan': ['ajar'],
      'basaLemesBatur': ['wulang,wuruk'],
      'bahasaIndonesia': ['mengajar'],
    },
    {
      'basaLoma': ['aji'],
      'basaLemesSorangan': ['aji'],
      'basaLemesBatur': ['aos'],
      'bahasaIndonesia': ['mengaji'],
    },
    {
      'basaLoma': ['aju'],
      'basaLemesSorangan': ['ajeng'],
      'basaLemesBatur': ['ajeng'],
      'bahasaIndonesia': ['menyampaikan'],
    },
    {
      'basaLoma': ['akang'],
      'basaLemesSorangan': ['akang'],
      'basaLemesBatur': ['engkang'],
      'bahasaIndonesia': ['kakak'],
    },
    {
      'basaLoma': ['aki'],
      'basaLemesSorangan': ['(pun)aki'],
      'basaLemesBatur': ['(tuang) eyang'],
      'bahasaIndonesia': ['kakek'],
    },
    {
      'basaLoma': ['aku'],
      'basaLemesSorangan': ['angken'],
      'basaLemesBatur': ['angken'],
      'bahasaIndonesia': ['mengaku'],
    },
    {
      'basaLoma': ['ali'],
      'basaLemesSorangan': ['ali,cingcing'],
      'basaLemesBatur': ['lelepen'],
      'bahasaIndonesia': ['cincin'],
    },
    {
      'basaLoma': ['alo'],
      'basaLemesSorangan': ['(pun) alo'],
      'basaLemesBatur': ['kapiputra'],
      'bahasaIndonesia': ['keponakan'],
    },
    {
      'basaLoma': ['alus'],
      'basaLemesSorangan': ['saé'],
      'basaLemesBatur': ['saé'],
      'bahasaIndonesia': ['bagus'],
    },
    {
      'basaLoma': ['ambéh'],
      'basaLemesSorangan': ['supados'],
      'basaLemesBatur': ['supados'],
      'bahasaIndonesia': ['supaya'],
    },
    {
      'basaLoma': ['ambek'],
      'basaLemesSorangan': ['ambek'],
      'basaLemesBatur': ['bendu, wera'],
      'bahasaIndonesia': ['marah'],
    },
    {
      'basaLoma': ['ambeu'],
      'basaLemesSorangan': ['ambeu'],
      'basaLemesBatur': ['ambung'],
      'bahasaIndonesia': ['mencium bau'],
    },
    {
      'basaLoma': ['amit'],
      'basaLemesSorangan': ['permios'],
      'basaLemesBatur': ['permios'],
      'bahasaIndonesia': ['pamit'],
    },
    {
      'basaLoma': ['amitan'],
      'basaLemesSorangan': ['permios'],
      'basaLemesBatur': ['permios'],
      'bahasaIndonesia': ['permisi'],
    },
    {
      'basaLoma': ['amprok'],
      'basaLemesSorangan': ['tepang'],
      'basaLemesBatur': ['tepang'],
      'bahasaIndonesia': ['bertemu'],
    },
    {
      'basaLoma': ['anak'],
      'basaLemesSorangan': ['(pun) anak'],
      'basaLemesBatur': ['(tuang) putra'],
      'bahasaIndonesia': ['anak'],
    },
    {
      'basaLoma': ['anco'],
      'basaLemesSorangan': ['cawis'],
      'basaLemesBatur': ['cawis'],
      'bahasaIndonesia': ['kerangka'],
    },
    {
      'basaLoma': ['anggang'],
      'basaLemesSorangan': ['tebih'],
      'basaLemesBatur': ['tebih'],
      'bahasaIndonesia': ['jauh'],
    },
    {
      'basaLoma': ['anggel'],
      'basaLemesSorangan': ['bantal'],
      'basaLemesBatur': ['bantal, kajang mastaka'],
      'bahasaIndonesia': ['bantal'],
    },
    {
      'basaLoma': ['anggeus'],
      'basaLemesSorangan': ['atos, parantos, réngsé'],
      'basaLemesBatur': ['atos, parantos'],
      'bahasaIndonesia': ['sudah'],
    },
    {
      'basaLoma': ['angir'],
      'basaLemesSorangan': ['kuramas'],
      'basaLemesBatur': ['kujamas'],
      'bahasaIndonesia': ['keramas'],
    },
    {
      'basaLoma': ['angkir'],
      'basaLemesSorangan': ['ulem, haturanan calik'],
      'basaLemesBatur': ['ulem, haturanan calik'],
      'bahasaIndonesia': ['undang'],
    },
    {
      'basaLoma': ['anjang'],
      'basaLemesSorangan': ['deuheus'],
      'basaLemesBatur': ['tatamu'],
      'bahasaIndonesia': ['bertamu'],
    },
    {
      'basaLoma': ['antara'],
      'basaLemesSorangan': ['antawis'],
      'basaLemesBatur': ['antawis'],
      'bahasaIndonesia': ['antara'],
    },
    {
      'basaLoma': ['anteur'],
      'basaLemesSorangan': ['jajap'],
      'basaLemesBatur': ['sarengan'],
      'bahasaIndonesia': ['antara'],
    },
    {
      'basaLoma': ['anti'],
      'basaLemesSorangan': ['antos'],
      'basaLemesBatur': ['antos'],
      'bahasaIndonesia': ['tunggu'],
    },
    {
      'basaLoma': ['anyar'],
      'basaLemesSorangan': ['anyar'],
      'basaLemesBatur': ['anyar'],
      'bahasaIndonesia': ['baru'],
    },
    {
      'basaLoma': ['anyaran'],
      'basaLemesSorangan': ['nembéan'],
      'basaLemesBatur': ['nembéan'],
      'bahasaIndonesia': ['baru'],
    },
    {
      'basaLoma': ['arang'],
      'basaLemesSorangan': ['awis, awis-awis'],
      'basaLemesBatur': ['awis, awis-awis'],
      'bahasaIndonesia': ['mahal'],
    },
    {
      'basaLoma': ['arék'],
      'basaLemesSorangan': ['badé, seja'],
      'basaLemesBatur': ['badé, seja'],
      'bahasaIndonesia': ['akan'],
    },
    {
      'basaLoma': ['arep'],
      'basaLemesSorangan': ['ajeng'],
      'basaLemesBatur': ['ajeng'],
      'bahasaIndonesia': ['harap'],
    },
    {
      'basaLoma': ['ari'],
      'basaLemesSorangan': ['dupi, upami'],
      'basaLemesBatur': ['dupi, upami'],
      'bahasaIndonesia': ['kalau'],
    },
    {
      'basaLoma': ['asa'],
      'basaLemesSorangan': ['raos'],
      'basaLemesBatur': ['raos'],
      'bahasaIndonesia': ['perasaan'],
    },
    {
      'basaLoma': ['asal'],
      'basaLemesSorangan': ['kawit'],
      'basaLemesBatur': ['awit, kawit'],
      'bahasaIndonesia': ['mula'],
    },
    {
      'basaLoma': ['aso'],
      'basaLemesSorangan': ['aso'],
      'basaLemesBatur': ['leleson'],
      'bahasaIndonesia': ['istirahat'],
    },
    {
      'basaLoma': ['astana'],
      'basaLemesSorangan': ['makam, pajaratan, pasaréan'],
      'basaLemesBatur': ['makam, pajaratan, pasaréan'],
      'bahasaIndonesia': ['kuburan'],
    },
    {
      'basaLoma': ['asup'],
      'basaLemesSorangan': ['lebet'],
      'basaLemesBatur': ['lebet'],
      'bahasaIndonesia': ['masuk'],
    },
    {
      'basaLoma': ['atawi'],
      'basaLemesSorangan': ['atanapi'],
      'basaLemesBatur': ['atanapi'],
      'bahasaIndonesia': ['atau'],
    },
    {
      'basaLoma': ['ati-ati'],
      'basaLemesSorangan': ['ati-ati'],
      'basaLemesBatur': ['atos-atos'],
      'bahasaIndonesia': ['awas, hati-hati'],
    },
    {
      'basaLoma': ['atoh'],
      'basaLemesSorangan': ['bingah'],
      'basaLemesBatur': ['bingah'],
      'bahasaIndonesia': ['senang'],
    },
    {
      'basaLoma': ['awak'],
      'basaLemesSorangan': ['awak'],
      'basaLemesBatur': ['salira'],
      'bahasaIndonesia': ['badan'],
    },
    {
      'basaLoma': ['awéwé'],
      'basaLemesSorangan': ['awéwé'],
      'basaLemesBatur': ['istri'],
      'bahasaIndonesia': ['perempuan'],
    },
    {
      'basaLoma': ['aya'],
      'basaLemesSorangan': ['aya'],
      'basaLemesBatur': ['aya'],
      'bahasaIndonesia': ['ada'],
    },
    {
      'basaLoma': ['babantu'],
      'basaLemesSorangan': ['babantu'],
      'basaLemesBatur': ['babantos'],
      'bahasaIndonesia': ['membantu'],
    },
    {
      'basaLoma': ['babari'],
      'basaLemesSorangan': ['gampil'],
      'basaLemesBatur': ['gampil'],
      'bahasaIndonesia': ['mudah'],
    },
    {
      'basaLoma': ['babatang'],
      'basaLemesSorangan': ['mayit'],
      'basaLemesBatur': ['layon'],
      'bahasaIndonesia': ['jenazah'],
    },
    {
      'basaLoma': ['babaturan'],
      'basaLemesSorangan': ['réréncangan'],
      'basaLemesBatur': ['réréncangan'],
      'bahasaIndonesia': ['teman'],
    },
    {
      'basaLoma': ['baca'],
      'basaLemesSorangan': ['aos'],
      'basaLemesBatur': ['aos'],
      'bahasaIndonesia': ['baca'],
    },
    {
      'basaLoma': ['badag'],
      'basaLemesSorangan': ['ageung'],
      'basaLemesBatur': ['ageung'],
      'bahasaIndonesia': ['besar'],
    },
    {
      'basaLoma': ['badami'],
      'basaLemesSorangan': ['badanten'],
      'basaLemesBatur': ['badanten'],
      'bahasaIndonesia': ['bermusyawarah'],
    },
    {
      'basaLoma': ['badan'],
      'basaLemesSorangan': ['badan'],
      'basaLemesBatur': ['salira'],
      'bahasaIndonesia': ['badan'],
    },
    {
      'basaLoma': ['badarat'],
      'basaLemesSorangan': ['badarat'],
      'basaLemesBatur': ['nyacat'],
      'bahasaIndonesia': ['mendarat'],
    },
    {
      'basaLoma': ['badéga'],
      'basaLemesSorangan': ['réncang'],
      'basaLemesBatur': ['réncang'],
      'bahasaIndonesia': ['kawan'],
    },
    {
      'basaLoma': ['baé'],
      'basaLemesSorangan': ['sawios, teu sawios, wios'],
      'basaLemesBatur': ['sawios, teu sawios, wios'],
      'bahasaIndonesia': ['tidak apa-apa'],
    },
    {
      'basaLoma': ['baganti'],
      'basaLemesSorangan': ['bagentos'],
      'basaLemesBatur': ['bagentos'],
      'bahasaIndonesia': ['berganti'],
    },
    {
      'basaLoma': ['bagéa'],
      'basaLemesSorangan': ['haturan'],
      'basaLemesBatur': ['haturan'],
      'bahasaIndonesia': ['selamat, silahkan'],
    },
    {
      'basaLoma': ['bagéan'],
      'basaLemesSorangan': ['bagéan'],
      'basaLemesBatur': ['hancengan'],
      'bahasaIndonesia': ['bagian'],
    },
    {
      'basaLoma': ['bageur'],
      'basaLemesSorangan': ['bageur'],
      'basaLemesBatur': ['saé manah'],
      'bahasaIndonesia': ['baik'],
    },
    {
      'basaLoma': ['bagilir'],
      'basaLemesSorangan': ['bagentos'],
      'basaLemesBatur': ['bagentos'],
      'bahasaIndonesia': ['bergilir'],
    },
    {
      'basaLoma': ['baheula'],
      'basaLemesSorangan': ['kapungkur'],
      'basaLemesBatur': ['kapungkur'],
      'bahasaIndonesia': ['dahulu'],
    },
    {
      'basaLoma': ['baju'],
      'basaLemesSorangan': ['baju'],
      'basaLemesBatur': ['anggéan, anggoan, raksukan'],
      'bahasaIndonesia': ['pakaian'],
    },
    {
      'basaLoma': ['bakal'],
      'basaLemesSorangan': ['badé, seja'],
      'basaLemesBatur': ['badé, seja'],
      'bahasaIndonesia': ['akan'],
    },
    {
      'basaLoma': ['bakti'],
      'basaLemesSorangan': ['baktos'],
      'basaLemesBatur': ['baktos'],
      'bahasaIndonesia': ['bakti'],
    },
    {
      'basaLoma': ['balik'],
      'basaLemesSorangan': ['wangsul'],
      'basaLemesBatur': ['mulih'],
      'bahasaIndonesia': ['pulang'],
    },
    {
      'basaLoma': ['balur'],
      'basaLemesSorangan': ['balur'],
      'basaLemesBatur': ['lulur, pupur'],
      'bahasaIndonesia': ['teman, handai'],
    },
    {
      'basaLoma': ['bangga'],
      'basaLemesSorangan': ['abot, sesah'],
      'basaLemesBatur': ['abot, sesah'],
      'bahasaIndonesia': ['susah'],
    },
    {
      'basaLoma': ['bangun'],
      'basaLemesSorangan': ['bangun'],
      'basaLemesBatur': ['sapertos'],
      'bahasaIndonesia': ['seperti'],
    },
    {
      'basaLoma': ['bantu'],
      'basaLemesSorangan': ['bantu'],
      'basaLemesBatur': ['bantos'],
      'bahasaIndonesia': ['bantu'],
    },
    {
      'basaLoma': ['bapa'],
      'basaLemesSorangan': ['(pun) bapa'],
      'basaLemesBatur': ['(tuang) rama'],
      'bahasaIndonesia': ['ayah, bapak'],
    },
    {
      'basaLoma': ['baraya'],
      'basaLemesSorangan': ['réréhan, sadérék'],
      'basaLemesBatur': ['wargi'],
      'bahasaIndonesia': ['saudara'],
    },
    {
      'basaLoma': ['barempug'],
      'basaLemesSorangan': ['barempug'],
      'basaLemesBatur': ['barempag'],
      'bahasaIndonesia': ['bermusyawarah'],
    },
    {
      'basaLoma': ['bareng'],
      'basaLemesSorangan': ['sareng'],
      'basaLemesBatur': ['sareng'],
      'bahasaIndonesia': ['bersama'],
    },
    {
      'basaLoma': ['baréto'],
      'basaLemesSorangan': ['kapungkur'],
      'basaLemesBatur': ['kapungkur'],
      'bahasaIndonesia': ['dahulu'],
    },
    {
      'basaLoma': ['basa'],
      'basaLemesSorangan': ['nalika, waktos'],
      'basaLemesBatur': ['nalika, waktos'],
      'bahasaIndonesia': ['waktu'],
    },
    {
      'basaLoma': ['batuk'],
      'basaLemesSorangan': ['batuk'],
      'basaLemesBatur': ['gohgoy'],
      'bahasaIndonesia': ['batuk'],
    },
    {
      'basaLoma': ['batur'],
      'basaLemesSorangan': ['réncang'],
      'basaLemesBatur': ['réncang'],
      'bahasaIndonesia': ['teman'],
    },
    {
      'basaLoma': ['bawa'],
      'basaLemesSorangan': ['bantun'],
      'basaLemesBatur': ['candak'],
      'bahasaIndonesia': ['bawa'],
    },
    {
      'basaLoma': ['bawirasa'],
      'basaLemesSorangan': ['bawiraos, ku émutan'],
      'basaLemesBatur': ['bawiraos, ku émutan'],
      'bahasaIndonesia': ['meskipun'],
    },
    {
      'basaLoma': ['béak'],
      'basaLemesSorangan': ['séép'],
      'basaLemesBatur': ['séép'],
      'bahasaIndonesia': ['habis'],
    },
    {
      'basaLoma': ['bébéja'],
      'basaLemesSorangan': ['nyanggem, popoyan, unjukan, wawartos'],
      'basaLemesBatur': ['nyarios, pupulih, unjukan, wawartos'],
      'bahasaIndonesia': ['kabar, mengabari'],
    },
    {
      'basaLoma': ['béda'],
      'basaLemesSorangan': ['bénten'],
      'basaLemesBatur': ['bénten'],
      'bahasaIndonesia': ['beda'],
    },
    {
      'basaLoma': ['begang'],
      'basaLemesSorangan': ['begang'],
      'basaLemesBatur': ['langsip, langsit'],
      'bahasaIndonesia': ['kurus'],
    },
    {
      'basaLoma': ['begéng'],
      'basaLemesSorangan': ['begang'],
      'basaLemesBatur': ['langsip, langsit'],
      'bahasaIndonesia': ['kurus'],
    },
    {
      'basaLoma': ['béja'],
      'basaLemesSorangan': ['wartos'],
      'basaLemesBatur': ['wartos'],
      'bahasaIndonesia': ['kabar, mengabari'],
    },
    {
      'basaLoma': ['belah'],
      'basaLemesSorangan': ['palih'],
      'basaLemesBatur': ['palih'],
      'bahasaIndonesia': ['sebelah'],
    },
    {
      'basaLoma': ['bendo'],
      'basaLemesSorangan': ['bendo'],
      'basaLemesBatur': ['udeng'],
      'bahasaIndonesia': ['blangkon'],
    },
    {
      'basaLoma': ['bener'],
      'basaLemesSorangan': ['leres'],
      'basaLemesBatur': ['leres'],
      'bahasaIndonesia': ['betul'],
    },
    {
      'basaLoma': ['bengék'],
      'basaLemesSorangan': ['asma'],
      'basaLemesBatur': ['ampeg'],
      'bahasaIndonesia': ['asma'],
    },
    {
      'basaLoma': ['béré'],
      'basaLemesSorangan': ['pasihan'],
      'basaLemesBatur': ['haturan(an), lélér, paparin'],
      'bahasaIndonesia': ['memberi'],
    },
    {
      'basaLoma': ['berekah'],
      'basaLemesSorangan': ['aya hibar, pangésto, pangéstu'],
      'basaLemesBatur': ['damang, wilujeng'],
      'bahasaIndonesia': ['sehat'],
    },
    {
      'basaLoma': ['bésan'],
      'basaLemesSorangan': ['bésan'],
      'basaLemesBatur': ['warang'],
      'bahasaIndonesia': ['besan'],
    },
    {
      'basaLoma': ['beubeur'],
      'basaLemesSorangan': ['beubeur, sabuk'],
      'basaLemesBatur': ['beulitan'],
      'bahasaIndonesia': ['sabuk'],
    },
    {
      'basaLoma': ['beuheung'],
      'basaLemesSorangan': ['beuheung'],
      'basaLemesBatur': ['tenggek'],
      'bahasaIndonesia': ['leher'],
    },
    {
      'basaLoma': ['beuki'],
      'basaLemesSorangan': ['seneng'],
      'basaLemesBatur': ['sedep'],
      'bahasaIndonesia': ['suka'],
    },
    {
      'basaLoma': ['beulah'],
      'basaLemesSorangan': ['palih'],
      'basaLemesBatur': ['palih'],
      'bahasaIndonesia': ['sebelah'],
    },
    {
      'basaLoma': ['beulah (Jadi 2)'],
      'basaLemesSorangan': ['beulah'],
      'basaLemesBatur': ['beulah'],
      'bahasaIndonesia': ['belah'],
    },
    {
      'basaLoma': ['beuli'],
      'basaLemesSorangan': ['pésér'],
      'basaLemesBatur': ['galeuh'],
      'bahasaIndonesia': ['beli'],
    },
    {
      'basaLoma': ['beunang'],
      'basaLemesSorangan': ['kénging'],
      'basaLemesBatur': ['kénging'],
      'bahasaIndonesia': ['dapat'],
    },
    {
      'basaLoma': ['beungeut'],
      'basaLemesSorangan': ['beungeut'],
      'basaLemesBatur': ['pameunteu, raray'],
      'bahasaIndonesia': ['wajah'],
    },
    {
      'basaLoma': ['beurang'],
      'basaLemesSorangan': ['siang'],
      'basaLemesBatur': ['siang'],
      'bahasaIndonesia': ['siang'],
    },
    {
      'basaLoma': ['beurat'],
      'basaLemesSorangan': ['abot'],
      'basaLemesBatur': ['abot'],
      'bahasaIndonesia': ['berat'],
    },
    {
      'basaLoma': ['beuteung'],
      'basaLemesSorangan': ['beuteung, padaharan'],
      'basaLemesBatur': ['lambut, patuangan'],
      'bahasaIndonesia': ['perut'],
    },
    {
      'basaLoma': ['bibi'],
      'basaLemesSorangan': ['(pun) bibi'],
      'basaLemesBatur': ['(tuang) ibu'],
      'bahasaIndonesia': ['bibi'],
    },
    {
      'basaLoma': ['bijil'],
      'basaLemesSorangan': ['medal'],
      'basaLemesBatur': ['medal'],
      'bahasaIndonesia': ['keluar'],
    },
    {
      'basaLoma': ['bikeun'],
      'basaLemesSorangan': ['paparinkeun, pasihkeun'],
      'basaLemesBatur': ['haturkeun, lélérkeun, sanggakeun'],
      'bahasaIndonesia': ['memberikan'],
    },
    {
      'basaLoma': ['bilang'],
      'basaLemesSorangan': ['étang'],
      'basaLemesBatur': ['étang'],
      'bahasaIndonesia': ['menghitung'],
    },
    {
      'basaLoma': ['bingung'],
      'basaLemesSorangan': ['éwed'],
      'basaLemesBatur': ['éwed'],
      'bahasaIndonesia': ['bingung'],
    },
    {
      'basaLoma': ['bireungeuh'],
      'basaLemesSorangan': ['bireungeuh, tingal'],
      'basaLemesBatur': ['tingali'],
      'bahasaIndonesia': ['melihat'],
    },
    {
      'basaLoma': ['birit'],
      'basaLemesSorangan': ['birit, bujur'],
      'basaLemesBatur': ['imbit'],
      'bahasaIndonesia': ['pantat'],
    },
    {
      'basaLoma': ['bisa'],
      'basaLemesSorangan': ['tiasa'],
      'basaLemesBatur': ['iasa'],
      'bahasaIndonesia': ['bisa'],
    },
    {
      'basaLoma': ['bisa jadi'],
      'basaLemesSorangan': ['tiasa janten'],
      'basaLemesBatur': ['tiasa janten'],
      'bahasaIndonesia': ['bisa jadi'],
    },
    {
      'basaLoma': ['bisi'],
      'basaLemesSorangan': ['bilih'],
      'basaLemesBatur': ['bilih'],
      'bahasaIndonesia': ['mungkin'],
    },
    {
      'basaLoma': ['bisul'],
      'basaLemesSorangan': ['bisul'],
      'basaLemesBatur': ['gambuh'],
      'bahasaIndonesia': ['bisul'],
    },
    {
      'basaLoma': ['bitis'],
      'basaLemesSorangan': ['bitis'],
      'basaLemesBatur': ['wentis'],
      'bahasaIndonesia': ['betis'],
    },
    {
      'basaLoma': ['biwir'],
      'basaLemesSorangan': ['biwir'],
      'basaLemesBatur': ['lambé, lambey'],
      'bahasaIndonesia': ['bibir'],
    },
    {
      'basaLoma': ['boa'],
      'basaLemesSorangan': ['tiasa janten'],
      'basaLemesBatur': ['tiasa janten'],
      'bahasaIndonesia': ['bisa jadi'],
    },
    {
      'basaLoma': ['boga'],
      'basaLemesSorangan': ['gaduh'],
      'basaLemesBatur': ['kagungan'],
      'bahasaIndonesia': ['punya'],
    },
    {
      'basaLoma': ['bolonan'],
      'basaLemesSorangan': ['kareseban, udur sasih'],
      'basaLemesBatur': ['kareseban'],
      'bahasaIndonesia': ['haid'],
    },
    {
      'basaLoma': ['boro'],
      'basaLemesSorangan': ['bujeng'],
      'basaLemesBatur': ['bujeng'],
      'bahasaIndonesia': ['kesampaian'],
    },
    {
      'basaLoma': ['boro-boro'],
      'basaLemesSorangan': ['bujeng-bujeng'],
      'basaLemesBatur': ['bujeng-bujeng'],
      'bahasaIndonesia': ['jangankan'],
    },
    {
      'basaLoma': ['buang'],
      'basaLemesSorangan': ['piceun'],
      'basaLemesBatur': ['beuratan'],
      'bahasaIndonesia': ['buang'],
    },
    {
      'basaLoma': ['bubuang'],
      'basaLemesSorangan': ['miceun'],
      'basaLemesBatur': ['kabeuratan'],
      'bahasaIndonesia': ['membuang'],
    },
    {
      'basaLoma': ['budak'],
      'basaLemesSorangan': ['budak'],
      'basaLemesBatur': ['murangkalih'],
      'bahasaIndonesia': ['anak kecil'],
    },
    {
      'basaLoma': ['bujal'],
      'basaLemesSorangan': ['bujal'],
      'basaLemesBatur': ['udel, puser'],
      'bahasaIndonesia': ['pusar'],
    },
    {
      'basaLoma': ['bujur'],
      'basaLemesSorangan': ['birit, bujur'],
      'basaLemesBatur': ['imbit'],
      'bahasaIndonesia': ['pantat'],
    },
    {
      'basaLoma': ['buka (puasa)'],
      'basaLemesSorangan': ['buka'],
      'basaLemesBatur': ['bobor'],
      'bahasaIndonesia': ['buka puasa'],
    },
    {
      'basaLoma': ['bukti'],
      'basaLemesSorangan': ['buktos'],
      'basaLemesBatur': ['buktos'],
      'bahasaIndonesia': ['bukti'],
    },
    {
      'basaLoma': ['bulan'],
      'basaLemesSorangan': ['sasih'],
      'basaLemesBatur': ['sasih'],
      'bahasaIndonesia': ['bulan'],
    },
    {
      'basaLoma': ['bulan puasa'],
      'basaLemesSorangan': ['sasih siam'],
      'basaLemesBatur': ['sasih siam'],
      'bahasaIndonesia': ['bulan puasa'],
    },
    {
      'basaLoma': ['bungah'],
      'basaLemesSorangan': ['bingah'],
      'basaLemesBatur': ['bingah'],
      'bahasaIndonesia': ['senang, gembira'],
    },
    {
      'basaLoma': ['bungsu'],
      'basaLemesSorangan': ['bungsu'],
      'basaLemesBatur': ['putra pangalitna'],
      'bahasaIndonesia': ['bungsu'],
    },
    {
      'basaLoma': ['burit'],
      'basaLemesSorangan': ['sonten'],
      'basaLemesBatur': ['sonten'],
      'bahasaIndonesia': ['sore'],
    },
    {
      'basaLoma': ['buru'],
      'basaLemesSorangan': ['buru, énggal'],
      'basaLemesBatur': ['buru, énggal'],
      'bahasaIndonesia': ['lekas'],
    },
    {
      'basaLoma': ['butuh'],
      'basaLemesSorangan': ['peryogi'],
      'basaLemesBatur': ['peryogi'],
      'bahasaIndonesia': ['butuh'],
    },
    {
      'basaLoma': ['buuk'],
      'basaLemesSorangan': ['buuk'],
      'basaLemesBatur': ['rambut'],
      'bahasaIndonesia': ['rambut'],
    },
    {
      'basaLoma': ['cabak'],
      'basaLemesSorangan': ['cabak'],
      'basaLemesBatur': ['cepeng'],
      'bahasaIndonesia': ['memegang'],
    },
    {
      'basaLoma': ['cacangkir'],
      'basaLemesSorangan': ['cacangkir'],
      'basaLemesBatur': ['tangkepan'],
      'bahasaIndonesia': ['cangkir'],
    },
    {
      'basaLoma': ['cageur'],
      'basaLemesSorangan': ['pangésto, pangéstu'],
      'basaLemesBatur': ['damang'],
      'bahasaIndonesia': ['sehat'],
    },
    {
      'basaLoma': ['calana'],
      'basaLemesSorangan': ['calana'],
      'basaLemesBatur': ['lancingan'],
      'bahasaIndonesia': ['celana'],
    },
    {
      'basaLoma': ['can'],
      'basaLemesSorangan': ['teu acan'],
      'basaLemesBatur': ['teu acan'],
      'bahasaIndonesia': ['belum'],
    },
    {
      'basaLoma': ['candung'],
      'basaLemesSorangan': ['wayuh'],
      'basaLemesBatur': ['wayuh'],
      'bahasaIndonesia': ['dimadu'],
    },
    {
      'basaLoma': ['caneut'],
      'basaLemesSorangan': ['caneut'],
      'basaLemesBatur': ['leueut'],
      'bahasaIndonesia': ['makan'],
    },
    {
      'basaLoma': ['cangkéng'],
      'basaLemesSorangan': ['cangkéng'],
      'basaLemesBatur': ['angkéng'],
      'bahasaIndonesia': ['pinggang'],
    },
    {
      'basaLoma': ['cangkeul'],
      'basaLemesSorangan': ['cangkeul'],
      'basaLemesBatur': ['pegel'],
      'bahasaIndonesia': ['pegal'],
    },
    {
      'basaLoma': ['cangkir'],
      'basaLemesSorangan': ['cangkir'],
      'basaLemesBatur': ['tangkep'],
      'bahasaIndonesia': ['cangkir'],
    },
    {
      'basaLoma': ['capé'],
      'basaLemesSorangan': ['capé'],
      'basaLemesBatur': ['palay'],
      'bahasaIndonesia': ['lelah'],
    },
    {
      'basaLoma': ['cara'],
      'basaLemesSorangan': ['sapertos'],
      'basaLemesBatur': ['sapertos'],
      'bahasaIndonesia': ['seperti'],
    },
    {
      'basaLoma': ['caram'],
      'basaLemesSorangan': ['carék, caram'],
      'basaLemesBatur': ['wagel'],
      'bahasaIndonesia': ['memarahi'],
    },
    {
      'basaLoma': ['carang'],
      'basaLemesSorangan': ['awis, awis-awis'],
      'basaLemesBatur': ['awis, awis-awis'],
      'bahasaIndonesia': ['jarang'],
    },
    {
      'basaLoma': ['carécét'],
      'basaLemesSorangan': ['saputangan'],
      'basaLemesBatur': ['salempay'],
      'bahasaIndonesia': ['saputangan'],
    },
    {
      'basaLoma': ['carék'],
      'basaLemesSorangan': ['carék, caram'],
      'basaLemesBatur': ['wagel'],
      'bahasaIndonesia': ['memarahi'],
    },
    {
      'basaLoma': ['carékan'],
      'basaLemesSorangan': ['carékan'],
      'basaLemesBatur': ['seuseulan'],
      'bahasaIndonesia': ['memarahi'],
    },
    {
      'basaLoma': ['carita'],
      'basaLemesSorangan': ['sanggem'],
      'basaLemesBatur': ['carios'],
      'bahasaIndonesia': ['berbicara, bercerita'],
    },
    {
      'basaLoma': ['caritaan'],
      'basaLemesSorangan': ['sanggeman'],
      'basaLemesBatur': ['cariosan'],
      'bahasaIndonesia': ['pembicaraan'],
    },
    {
      'basaLoma': ['cécéwok'],
      'basaLemesSorangan': ['obéh, ombéh'],
      'basaLemesBatur': ['obéh, ombéh'],
      'bahasaIndonesia': ['cebok'],
    },
    {
      'basaLoma': ['cekel'],
      'basaLemesSorangan': ['cekel'],
      'basaLemesBatur': ['cepeng'],
      'bahasaIndonesia': ['memegang'],
    },
    {
      'basaLoma': ['cenah'],
      'basaLemesSorangan': ['cenah'],
      'basaLemesBatur': ['saurna'],
      'bahasaIndonesia': ['katanya'],
    },
    {
      'basaLoma': ['ceuk'],
      'basaLemesSorangan': ['sanggem'],
      'basaLemesBatur': ['saur'],
      'bahasaIndonesia': ['katanya'],
    },
    {
      'basaLoma': ['ceuli'],
      'basaLemesSorangan': ['ceuli'],
      'basaLemesBatur': ['cepil'],
      'bahasaIndonesia': ['telinga'],
    },
    {
      'basaLoma': ['ceurik'],
      'basaLemesSorangan': ['ceurik'],
      'basaLemesBatur': ['nangis, tangis'],
      'bahasaIndonesia': ['menangis'],
    },
    {
      'basaLoma': ['cici'],
      'basaLemesSorangan': ['cici'],
      'basaLemesBatur': ['pair'],
      'bahasaIndonesia': ['menuangkan'],
    },
    {
      'basaLoma': ['cicing'],
      'basaLemesSorangan': ['calik, matuh'],
      'basaLemesBatur': ['calik, linggih'],
      'bahasaIndonesia': ['diam'],
    },
    {
      'basaLoma': ['ciduh'],
      'basaLemesSorangan': ['ciduh'],
      'basaLemesBatur': ['ludah'],
      'bahasaIndonesia': ['ludah'],
    },
    {
      'basaLoma': ['cik'],
      'basaLemesSorangan': ['cobi'],
      'basaLemesBatur': ['cobi'],
      'bahasaIndonesia': ['mencoba'],
    },
    {
      'basaLoma': ['cikal'],
      'basaLemesSorangan': ['cikal'],
      'basaLemesBatur': ['putra pangageungna'],
      'bahasaIndonesia': ['anak sulung'],
    },
    {
      'basaLoma': ['cikiiih'],
      'basaLemesSorangan': ['cikahampangan'],
      'basaLemesBatur': ['cikahampangan'],
      'bahasaIndonesia': ['air kencing'],
    },
    {
      'basaLoma': ['ciling'],
      'basaLemesSorangan': ['jamban'],
      'basaLemesBatur': ['jamban'],
      'bahasaIndonesia': ['jamban, toilet'],
    },
    {
      'basaLoma': ['cing'],
      'basaLemesSorangan': ['cobi'],
      'basaLemesBatur': ['cobi'],
      'bahasaIndonesia': ['mencoba'],
    },
    {
      'basaLoma': ['cipanon'],
      'basaLemesSorangan': ['cipanon'],
      'basaLemesBatur': ['cisoca'],
      'bahasaIndonesia': ['air mata'],
    },
    {
      'basaLoma': ['ciri'],
      'basaLemesSorangan': ['tawis'],
      'basaLemesBatur': ['tawis'],
      'bahasaIndonesia': ['ciri'],
    },
    {
      'basaLoma': ['cium'],
      'basaLemesSorangan': ['cium'],
      'basaLemesBatur': ['ambung'],
      'bahasaIndonesia': ['mencium'],
    },
    {
      'basaLoma': ['coba'],
      'basaLemesSorangan': ['cobi'],
      'basaLemesBatur': ['cobi'],
      'bahasaIndonesia': ['mencoba'],
    },
    {
      'basaLoma': ['cocoba'],
      'basaLemesSorangan': ['cocobi'],
      'basaLemesBatur': ['cocobi'],
      'bahasaIndonesia': ['mencoba'],
    },
    {
      'basaLoma': ['cokot'],
      'basaLemesSorangan': ['bantun'],
      'basaLemesBatur': ['candak'],
      'bahasaIndonesia': ['mengambil'],
    },
    {
      'basaLoma': ['cukup'],
      'basaLemesSorangan': ['cekap'],
      'basaLemesBatur': ['cekap'],
      'bahasaIndonesia': ['cukup'],
    },
    {
      'basaLoma': ['cukur'],
      'basaLemesSorangan': ['cukur'],
      'basaLemesBatur': ['paras'],
      'bahasaIndonesia': ['cukur'],
    },
    {
      'basaLoma': ['cumpon'],
      'basaLemesSorangan': ['caos, cumpon'],
      'basaLemesBatur': ['caos'],
      'bahasaIndonesia': ['penuh'],
    },
    {
      'basaLoma': ['cunduk'],
      'basaLemesSorangan': ['dongkap'],
      'basaLemesBatur': ['rawuh, sumping'],
      'bahasaIndonesia': ['datang'],
    },
    {
      'basaLoma': ['daék'],
      'basaLemesSorangan': ['purun'],
      'basaLemesBatur': ['kersa'],
      'bahasaIndonesia': ['mau'],
    },
    {
      'basaLoma': ['dagang'],
      'basaLemesSorangan': ['dagang'],
      'basaLemesBatur': ['icalan'],
      'bahasaIndonesia': ['dagang'],
    },
    {
      'basaLoma': ['dago'],
      'basaLemesSorangan': ['antos'],
      'basaLemesBatur': ['antos'],
      'bahasaIndonesia': ['tunggu'],
    },
    {
      'basaLoma': ['dahar'],
      'basaLemesSorangan': ['neda, teda'],
      'basaLemesBatur': ['tuang'],
      'bahasaIndonesia': ['makan'],
    },
    {
      'basaLoma': ['dangdan'],
      'basaLemesSorangan': ['dangdan'],
      'basaLemesBatur': ['dangdos'],
      'bahasaIndonesia': ['dandan'],
    },
    {
      'basaLoma': ['dapur'],
      'basaLemesSorangan': ['dapur'],
      'basaLemesBatur': ['pawon'],
      'bahasaIndonesia': ['dapur'],
    },
    {
      'basaLoma': ['datang'],
      'basaLemesSorangan': ['dongkap'],
      'basaLemesBatur': ['rawuh, sumping'],
      'bahasaIndonesia': ['datang'],
    },
    {
      'basaLoma': ['déngé'],
      'basaLemesSorangan': ['kuping'],
      'basaLemesBatur': ['dangu'],
      'bahasaIndonesia': ['mendengar'],
    },
    {
      'basaLoma': ['deukeut'],
      'basaLemesSorangan': ['caket'],
      'basaLemesBatur': ['caket'],
      'bahasaIndonesia': ['dekat'],
    },
    {
      'basaLoma': ['deungen'],
      'basaLemesSorangan': ['réncang'],
      'basaLemesBatur': ['réncang'],
      'bahasaIndonesia': ['lauk'],
    },
    {
      'basaLoma': ['deungeun-deungeun'],
      'basaLemesSorangan': ['(nu) sanés'],
      'basaLemesBatur': ['(nu) sanés'],
      'bahasaIndonesia': ['orang lain, bukan saudara'],
    },
    {
      'basaLoma': ['déwék'],
      'basaLemesSorangan': ['abdi, sim kuring'],
      'basaLemesBatur': ['-'],
      'bahasaIndonesia': ['saya'],
    },
    {
      'basaLoma': ['diangir'],
      'basaLemesSorangan': ['dikuramas'],
      'basaLemesBatur': ['dikujamas'],
      'bahasaIndonesia': ['dikeramas'],
    },
    {
      'basaLoma': ['diangkir'],
      'basaLemesSorangan': ['diondang, disaur'],
      'basaLemesBatur': ['disaur, diulem'],
      'bahasaIndonesia': ['diundang'],
    },
    {
      'basaLoma': ['dicukur'],
      'basaLemesSorangan': ['dicukur'],
      'basaLemesBatur': ['diparas'],
      'bahasaIndonesia': ['dicukur'],
    },
    {
      'basaLoma': ['didik'],
      'basaLemesSorangan': ['atik'],
      'basaLemesBatur': ['tutur, wejang, wuruk'],
      'bahasaIndonesia': ['mendidik'],
    },
    {
      'basaLoma': ['didikan'],
      'basaLemesSorangan': ['atikan'],
      'basaLemesBatur': ['pitutur, piwejang, piwuruk'],
      'bahasaIndonesia': ['didikan'],
    },
    {
      'basaLoma': ['digusar'],
      'basaLemesSorangan': ['digusar'],
      'basaLemesBatur': ['dipeper'],
      'bahasaIndonesia': ['disunat'],
    },
    {
      'basaLoma': ['dikubur'],
      'basaLemesSorangan': ['dikaluat'],
      'basaLemesBatur': ['dikurebkeun'],
      'bahasaIndonesia': ['dikubur'],
    },
    {
      'basaLoma': ['dilétak'],
      'basaLemesSorangan': ['dilétak'],
      'basaLemesBatur': ['diliat'],
      'bahasaIndonesia': ['dijilat'],
    },
    {
      'basaLoma': ['dipalar'],
      'basaLemesSorangan': ['dipalar'],
      'basaLemesBatur': ['dipambrih, dipamrih'],
      'bahasaIndonesia': ['diharapkan'],
    },
    {
      'basaLoma': ['dipaparah'],
      'basaLemesSorangan': ['dikinten-kinten'],
      'basaLemesBatur': ['dikinten-kinten'],
      'bahasaIndonesia': ['dikira-kira'],
    },
    {
      'basaLoma': ['diri'],
      'basaLemesSorangan': ['diri'],
      'basaLemesBatur': ['salira'],
      'bahasaIndonesia': ['diri sendiri'],
    },
    {
      'basaLoma': ['disalin'],
      'basaLemesSorangan': ['(di)salin'],
      'basaLemesBatur': ['(di)gentos'],
      'bahasaIndonesia': ['diganti'],
    },
    {
      'basaLoma': ['ditaranjang'],
      'basaLemesSorangan': ['ditaranjang'],
      'basaLemesBatur': ['diwuwuda'],
      'bahasaIndonesia': ['telanjang'],
    },
    {
      'basaLoma': ['diuk'],
      'basaLemesSorangan': ['diuk'],
      'basaLemesBatur': ['calik, linggih'],
      'bahasaIndonesia': ['duduk'],
    },
    {
      'basaLoma': ['dosa'],
      'basaLemesSorangan': ['kalelepatan'],
      'basaLemesBatur': ['kalelepatan'],
      'bahasaIndonesia': ['dosa'],
    },
    {
      'basaLoma': ['dubur'],
      'basaLemesSorangan': ['dubur'],
      'basaLemesBatur': ['palawangan'],
      'bahasaIndonesia': ['dubur'],
    },
    {
      'basaLoma': ['dudukuy'],
      'basaLemesSorangan': ['dudukuy, topi'],
      'basaLemesBatur': ['langgukan, tudung'],
      'bahasaIndonesia': ['topi'],
    },
    {
      'basaLoma': ['duga'],
      'basaLemesSorangan': ['kinten'],
      'basaLemesBatur': ['kinten'],
      'bahasaIndonesia': ['duga'],
    },
    {
      'basaLoma': ['duit'],
      'basaLemesSorangan': ['artos'],
      'basaLemesBatur': ['artos'],
      'bahasaIndonesia': ['duit, uang'],
    },
    {
      'basaLoma': ['dulur'],
      'basaLemesSorangan': ['réréhan, sadérék'],
      'basaLemesBatur': ['wargi'],
      'bahasaIndonesia': ['saudara'],
    },
    {
      'basaLoma': ['duméh'],
      'basaLemesSorangan': ['jalaran, (ku) margi'],
      'basaLemesBatur': ['(ku) margi, réh(ing)'],
      'bahasaIndonesia': ['karena'],
    },
    {
      'basaLoma': ['éléh'],
      'basaLemesSorangan': ['éleh'],
      'basaLemesBatur': ['kawon'],
      'bahasaIndonesia': ['kalah'],
    },
    {
      'basaLoma': ['éling'],
      'basaLemesSorangan': ['émut'],
      'basaLemesBatur': ['émut'],
      'bahasaIndonesia': ['ingat'],
    },
    {
      'basaLoma': ['emang'],
      'basaLemesSorangan': ['(pun) paman'],
      'basaLemesBatur': ['(tuang) rama'],
      'bahasaIndonesia': ['paman'],
    },
    {
      'basaLoma': ['émboh'],
      'basaLemesSorangan': ['tambih'],
      'basaLemesBatur': ['tambih'],
      'bahasaIndonesia': ['tambah'],
    },
    {
      'basaLoma': ['embung'],
      'basaLemesSorangan': ['alim, narah (awéwé)'],
      'basaLemesBatur': ['alim, teu kersa'],
      'bahasaIndonesia': ['tidak mau'],
    },
    {
      'basaLoma': ['emét'],
      'basaLemesSorangan': ['kedik'],
      'basaLemesBatur': ['kedik'],
      'bahasaIndonesia': ['sedikit'],
    },
    {
      'basaLoma': ['encan'],
      'basaLemesSorangan': ['teu acan'],
      'basaLemesBatur': ['teu acan'],
      'bahasaIndonesia': ['belum'],
    },
    {
      'basaLoma': ['endeng'],
      'basaLemesSorangan': ['lami'],
      'basaLemesBatur': ['paos'],
      'bahasaIndonesia': ['lama'],
    },
    {
      'basaLoma': ['éndong'],
      'basaLemesSorangan': ['éndong'],
      'basaLemesBatur': ['kulem'],
      'bahasaIndonesia': ['menginap'],
    },
    {
      'basaLoma': ['enggeus'],
      'basaLemesSorangan': ['atos, parantos, réngsé'],
      'basaLemesBatur': ['atos, parantos'],
      'bahasaIndonesia': ['sudah'],
    },
    {
      'basaLoma': ['enggon'],
      'basaLemesSorangan': ['pamondokan'],
      'basaLemesBatur': ['pajuaran, pangkuleman'],
      'bahasaIndonesia': ['penginapan'],
    },
    {
      'basaLoma': ['entong'],
      'basaLemesSorangan': ['teu kénging'],
      'basaLemesBatur': ['teu kénging'],
      'bahasaIndonesia': ['tidak boleh'],
    },
    {
      'basaLoma': ['enya'],
      'basaLemesSorangan': ['leres, muhun, sumuhun, yaktos'],
      'basaLemesBatur': ['leres, muhun, sumuhun, yaktos'],
      'bahasaIndonesia': ['iya'],
    },
    {
      'basaLoma': ['enya-enya'],
      'basaLemesSorangan': ['leres-leres'],
      'basaLemesBatur': ['leres-leres'],
      'bahasaIndonesia': ['benar-benar'],
    },
    {
      'basaLoma': ['éra'],
      'basaLemesSorangan': ['isin'],
      'basaLemesBatur': ['lingsem'],
      'bahasaIndonesia': ['malu'],
    },
    {
      'basaLoma': ['éstu'],
      'basaLemesSorangan': ['ésto'],
      'basaLemesBatur': ['ésto'],
      'bahasaIndonesia': ['mengindahkan'],
    },
    {
      'basaLoma': ['eukeur'],
      'basaLemesSorangan': ['nuju'],
      'basaLemesBatur': ['nuju'],
      'bahasaIndonesia': ['sedang'],
    },
    {
      'basaLoma': ['eungap'],
      'basaLemesSorangan': ['sesek'],
      'basaLemesBatur': ['ampeg'],
      'bahasaIndonesia': ['sesak'],
    },
    {
      'basaLoma': ['eusi'],
      'basaLemesSorangan': ['lebetan'],
      'basaLemesBatur': ['lebetan'],
      'bahasaIndonesia': ['isi'],
    },
    {
      'basaLoma': ['eusian'],
      'basaLemesSorangan': ['lebetan'],
      'basaLemesBatur': ['lebetan'],
      'bahasaIndonesia': ['isinya'],
    },
    {
      'basaLoma': ['euweuh'],
      'basaLemesSorangan': ['teu aya'],
      'basaLemesBatur': ['teu aya'],
      'bahasaIndonesia': ['tidak ada'],
    },
    {
      'basaLoma': ['gado'],
      'basaLemesSorangan': ['gado'],
      'basaLemesBatur': ['angkeut'],
      'bahasaIndonesia': ['makan tanpa lauk'],
    },
    {
      'basaLoma': ['gagancangan'],
      'basaLemesSorangan': ['énggal-énggalan'],
      'basaLemesBatur': ['énggal-énggalan'],
      'bahasaIndonesia': ['cepat-cepat'],
    },
    {
      'basaLoma': ['gampang'],
      'basaLemesSorangan': ['gampil'],
      'basaLemesBatur': ['gampil'],
      'bahasaIndonesia': ['mudah'],
    },
    {
      'basaLoma': ['gancang'],
      'basaLemesSorangan': ['énggal'],
      'basaLemesBatur': ['énggal'],
      'bahasaIndonesia': ['cepat'],
    },
    {
      'basaLoma': ['gandék'],
      'basaLemesSorangan': ['réncang'],
      'basaLemesBatur': ['réncang'],
      'bahasaIndonesia': ['teman'],
    },
    {
      'basaLoma': ['gandéng'],
      'basaLemesSorangan': ['baribin'],
      'basaLemesBatur': ['baribin'],
      'bahasaIndonesia': ['berisik'],
    },
    {
      'basaLoma': ['ganti'],
      'basaLemesSorangan': ['gentos'],
      'basaLemesBatur': ['gentos'],
      'bahasaIndonesia': ['ganti'],
    },
    {
      'basaLoma': ['gardéng'],
      'basaLemesSorangan': ['gardéng'],
      'basaLemesBatur': ['lalangsé'],
      'bahasaIndonesia': ['abar'],
    },
    {
      'basaLoma': ['gawé'],
      'basaLemesSorangan': ['damel'],
      'basaLemesBatur': ['damel'],
      'bahasaIndonesia': ['kerja'],
    },
    {
      'basaLoma': ['gedé'],
      'basaLemesSorangan': ['ageung'],
      'basaLemesBatur': ['ageung'],
      'bahasaIndonesia': ['besar'],
    },
    {
      'basaLoma': ['gégél'],
      'basaLemesSorangan': ['gégél'],
      'basaLemesBatur': ['landep'],
      'bahasaIndonesia': ['gigit'],
    },
    {
      'basaLoma': ['gelung'],
      'basaLemesSorangan': ['gelung'],
      'basaLemesBatur': ['sanggul'],
      'bahasaIndonesia': ['sanggul'],
    },
    {
      'basaLoma': ['genah'],
      'basaLemesSorangan': ['raos'],
      'basaLemesBatur': ['raos'],
      'bahasaIndonesia': ['enak'],
    },
    {
      'basaLoma': ['gering'],
      'basaLemesSorangan': ['udur'],
      'basaLemesBatur': ['teu damang'],
      'bahasaIndonesia': ['sakit'],
    },
    {
      'basaLoma': ['gering parna'],
      'basaLemesSorangan': ['udur répot'],
      'basaLemesBatur': ['teu damang wales'],
      'bahasaIndonesia': ['sakit parah'],
    },
    {
      'basaLoma': ['gero'],
      'basaLemesSorangan': ['saur'],
      'basaLemesBatur': ['gentra'],
      'bahasaIndonesia': ['panggil'],
    },
    {
      'basaLoma': ['getol'],
      'basaLemesSorangan': ['kersaan'],
      'basaLemesBatur': ['kersaan'],
      'bahasaIndonesia': ['rajin'],
    },
    {
      'basaLoma': ['geuing'],
      'basaLemesSorangan': ['émutan'],
      'basaLemesBatur': ['émutan'],
      'bahasaIndonesia': ['mengingatkan'],
    },
    {
      'basaLoma': ['geulang'],
      'basaLemesSorangan': ['geulang'],
      'basaLemesBatur': ['pinggel'],
      'bahasaIndonesia': ['gelang'],
    },
    {
      'basaLoma': ['geura'],
      'basaLemesSorangan': ['geura, mangga'],
      'basaLemesBatur': ['mangga'],
      'bahasaIndonesia': ['baiklah, silahkan'],
    },
    {
      'basaLoma': ['geus'],
      'basaLemesSorangan': ['atos, parantos, réngsé'],
      'basaLemesBatur': ['atos, parantos'],
      'bahasaIndonesia': ['sudah'],
    },
    {
      'basaLoma': ['geuwat'],
      'basaLemesSorangan': ['énggal, énggal-énggal'],
      'basaLemesBatur': ['énggal, énggal-énggal'],
      'bahasaIndonesia': ['cepat'],
    },
    {
      'basaLoma': ['gigir'],
      'basaLemesSorangan': ['gigir'],
      'basaLemesBatur': ['gédéng'],
      'bahasaIndonesia': ['sebelah, samping'],
    },
    {
      'basaLoma': ['gigireun'],
      'basaLemesSorangan': ['gigireun'],
      'basaLemesBatur': ['gédéngeun'],
      'bahasaIndonesia': ['sebelah, samping'],
    },
    {
      'basaLoma': ['gilir'],
      'basaLemesSorangan': ['gilir'],
      'basaLemesBatur': ['gentos'],
      'bahasaIndonesia': ['berganti'],
    },
    {
      'basaLoma': ['gimir'],
      'basaLemesSorangan': ['gimir'],
      'basaLemesBatur': ['rentag manah'],
      'bahasaIndonesia': ['jerih'],
    },
    {
      'basaLoma': ['goda'],
      'basaLemesSorangan': ['cobi'],
      'basaLemesBatur': ['cobi'],
      'bahasaIndonesia': ['goda'],
    },
    {
      'basaLoma': ['gogoda'],
      'basaLemesSorangan': ['cocobi'],
      'basaLemesBatur': ['cocobi'],
      'bahasaIndonesia': ['godaan'],
    },
    {
      'basaLoma': ['goréng'],
      'basaLemesSorangan': ['awon, teu saé'],
      'basaLemesBatur': ['awon, teu saé'],
      'bahasaIndonesia': ['jelek'],
    },
    {
      'basaLoma': ['gugu'],
      'basaLemesSorangan': ['tumut'],
      'basaLemesBatur': ['tumut'],
      'bahasaIndonesia': ['patuh'],
    },
    {
      'basaLoma': ['guguling'],
      'basaLemesSorangan': ['guguling'],
      'basaLemesBatur': ['pepedek'],
      'bahasaIndonesia': ['guling'],
    },
    {
      'basaLoma': ['gumbira'],
      'basaLemesSorangan': ['bingah'],
      'basaLemesBatur': ['bingah'],
      'bahasaIndonesia': ['gembira'],
    },
    {
      'basaLoma': ['gura-giru'],
      'basaLemesSorangan': ['gura-giru'],
      'basaLemesBatur': ['énggal-énggalan'],
      'bahasaIndonesia': ['segera, cepat-cepat'],
    },
    {
      'basaLoma': ['gusar'],
      'basaLemesSorangan': ['gusar'],
      'basaLemesBatur': ['peper'],
      'bahasaIndonesia': ['menyapukan tangan'],
    },
    {
      'basaLoma': ['haben'],
      'basaLemesSorangan': ['haben'],
      'basaLemesBatur': ['teras-terasan'],
      'bahasaIndonesia': ['terus-terusan'],
    },
    {
      'basaLoma': ['hadé'],
      'basaLemesSorangan': ['saé'],
      'basaLemesBatur': ['saé'],
      'bahasaIndonesia': ['baik, bagus'],
    },
    {
      'basaLoma': ['hadir'],
      'basaLemesSorangan': ['tungkulan, nungkulan'],
      'basaLemesBatur': ['(nga)luuhan'],
      'bahasaIndonesia': ['menghadiri'],
    },
    {
      'basaLoma': ['hal'],
      'basaLemesSorangan': ['perkawis'],
      'basaLemesBatur': ['perkawis'],
      'bahasaIndonesia': ['hal'],
    },
    {
      'basaLoma': ['halangan'],
      'basaLemesSorangan': ['pambengan'],
      'basaLemesBatur': ['pambengan'],
      'bahasaIndonesia': ['halangan'],
    },
    {
      'basaLoma': ['halis'],
      'basaLemesSorangan': ['halis'],
      'basaLemesBatur': ['kening'],
      'bahasaIndonesia': ['alis'],
    },
    {
      'basaLoma': ['hampura'],
      'basaLemesSorangan': ['hapunten'],
      'basaLemesBatur': ['haksama, haksami, hapunten'],
      'bahasaIndonesia': ['maaf'],
    },
    {
      'basaLoma': ['handeueun'],
      'basaLemesSorangan': ['gegetun'],
      'basaLemesBatur': ['gegetun'],
      'bahasaIndonesia': ['sayang sekali'],
    },
    {
      'basaLoma': ['hanjakal'],
      'basaLemesSorangan': ['gegetun'],
      'basaLemesBatur': ['gegetun'],
      'bahasaIndonesia': ['sayang sekali'],
    },
    {
      'basaLoma': ['harega'],
      'basaLemesSorangan': ['pangaos'],
      'basaLemesBatur': ['pangaos'],
      'bahasaIndonesia': ['harga'],
    },
    {
      'basaLoma': ['hareup'],
      'basaLemesSorangan': ['payun'],
      'basaLemesBatur': ['payun'],
      'bahasaIndonesia': ['depan'],
    },
    {
      'basaLoma': ['harga'],
      'basaLemesSorangan': ['pangaos'],
      'basaLemesBatur': ['pangaos'],
      'bahasaIndonesia': ['harga'],
    },
    {
      'basaLoma': ['harita'],
      'basaLemesSorangan': ['waktos éta'],
      'basaLemesBatur': ['waktos éta'],
      'bahasaIndonesia': ['waktu itu'],
    },
    {
      'basaLoma': ['hariwang'],
      'basaLemesSorangan': ['salempang'],
      'basaLemesBatur': ['rejag manah, salempang'],
      'bahasaIndonesia': ['khawatir'],
    },
    {
      'basaLoma': ['harti'],
      'basaLemesSorangan': ['hartos'],
      'basaLemesBatur': ['hartos'],
      'bahasaIndonesia': ['arti'],
    },
    {
      'basaLoma': ['haté'],
      'basaLemesSorangan': ['haté'],
      'basaLemesBatur': ['manah, galih'],
      'bahasaIndonesia': ['hati'],
    },
    {
      'basaLoma': ['hawatir'],
      'basaLemesSorangan': ['hawatos'],
      'basaLemesBatur': ['hawatos'],
      'bahasaIndonesia': ['khawatir'],
    },
    {
      'basaLoma': ['hayang'],
      'basaLemesSorangan': ['hoyong'],
      'basaLemesBatur': ['palay'],
      'bahasaIndonesia': ['mau'],
    },
    {
      'basaLoma': ['hayu'],
      'basaLemesSorangan': ['mangga'],
      'basaLemesBatur': ['mangga'],
      'bahasaIndonesia': ['ayo, silahkan'],
    },
    {
      'basaLoma': ['héd'],
      'basaLemesSorangan': ['kareseban, udur sasih'],
      'basaLemesBatur': ['kareseban'],
      'bahasaIndonesia': ['haid'],
    },
    {
      'basaLoma': ['hég'],
      'basaLemesSorangan': ['geura, mangga'],
      'basaLemesBatur': ['mangga'],
      'bahasaIndonesia': ['silahkan'],
    },
    {
      'basaLoma': ['hélok'],
      'basaLemesSorangan': ['hémeng'],
      'basaLemesBatur': ['hémeng'],
      'bahasaIndonesia': ['heran'],
    },
    {
      'basaLoma': ['hésé'],
      'basaLemesSorangan': ['sesah'],
      'basaLemesBatur': ['sesah'],
      'bahasaIndonesia': ['susah'],
    },
    {
      'basaLoma': ['heuay'],
      'basaLemesSorangan': ['heuay'],
      'basaLemesBatur': ['angob'],
      'bahasaIndonesia': ['menguap'],
    },
    {
      'basaLoma': ['heubeul'],
      'basaLemesSorangan': ['lami'],
      'basaLemesBatur': ['lami'],
      'bahasaIndonesia': ['lama'],
    },
    {
      'basaLoma': ['heug'],
      'basaLemesSorangan': ['mangga'],
      'basaLemesBatur': ['mangga'],
      'bahasaIndonesia': ['baiklah, silahkan'],
    },
    {
      'basaLoma': ['hili'],
      'basaLemesSorangan': ['liron'],
      'basaLemesBatur': ['gentos'],
      'bahasaIndonesia': ['tukar'],
    },
    {
      'basaLoma': ['hina'],
      'basaLemesSorangan': ['laip'],
      'basaLemesBatur': ['laip'],
      'bahasaIndonesia': ['aib'],
    },
    {
      'basaLoma': ['hirup'],
      'basaLemesSorangan': ['hirup'],
      'basaLemesBatur': ['jumeneng'],
      'bahasaIndonesia': ['hidup'],
    },
    {
      'basaLoma': ['hitut'],
      'basaLemesSorangan': ['bobos, kabobosan'],
      'basaLemesBatur': ['bobos, kabobosan'],
      'bahasaIndonesia': ['kentut'],
    },
    {
      'basaLoma': ['hudang'],
      'basaLemesSorangan': ['hudang'],
      'basaLemesBatur': ['gugah'],
      'bahasaIndonesia': ['bangun'],
    },
    {
      'basaLoma': ['huntu'],
      'basaLemesSorangan': ['huntu'],
      'basaLemesBatur': ['waos'],
      'bahasaIndonesia': ['gigi'],
    },
    {
      'basaLoma': ['hutang'],
      'basaLemesSorangan': ['piétangan, sambetan'],
      'basaLemesBatur': ['piétangan, sambetan'],
      'bahasaIndonesia': ['hutang'],
    },
    {
      'basaLoma': ['iber'],
      'basaLemesSorangan': ['wartos'],
      'basaLemesBatur': ['wartos'],
      'bahasaIndonesia': ['berita'],
    },
    {
      'basaLoma': ['idin'],
      'basaLemesSorangan': ['widi'],
      'basaLemesBatur': ['widi'],
      'bahasaIndonesia': ['izin'],
    },
    {
      'basaLoma': ['igel'],
      'basaLemesSorangan': ['ibing'],
      'basaLemesBatur': ['ibing'],
      'bahasaIndonesia': ['menari, joget'],
    },
    {
      'basaLoma': ['iket'],
      'basaLemesSorangan': ['iket, totopong'],
      'basaLemesBatur': ['totopong, udeng'],
      'bahasaIndonesia': ['blangkon'],
    },
    {
      'basaLoma': ['ilik'],
      'basaLemesSorangan': ['tingal'],
      'basaLemesBatur': ['tingali'],
      'bahasaIndonesia': ['melihat'],
    },
    {
      'basaLoma': ['ilikan'],
      'basaLemesSorangan': ['tingalan'],
      'basaLemesBatur': ['tingalian'],
      'bahasaIndonesia': ['melihat'],
    },
    {
      'basaLoma': ['ilu'],
      'basaLemesSorangan': ['iring'],
      'basaLemesBatur': ['iring'],
      'bahasaIndonesia': ['ikut'],
    },
    {
      'basaLoma': ['imah'],
      'basaLemesSorangan': ['rorompok'],
      'basaLemesBatur': ['bumi'],
      'bahasaIndonesia': ['rumah'],
    },
    {
      'basaLoma': ['impi'],
      'basaLemesSorangan': ['impén'],
      'basaLemesBatur': ['impén'],
      'bahasaIndonesia': ['mimpi'],
    },
    {
      'basaLoma': ['imut'],
      'basaLemesSorangan': ['imut'],
      'basaLemesBatur': ['mésem'],
      'bahasaIndonesia': ['tersenyum'],
    },
    {
      'basaLoma': ['incu'],
      'basaLemesSorangan': ['(pun) incu'],
      'basaLemesBatur': ['(tuang) putu'],
      'bahasaIndonesia': ['cucu'],
    },
    {
      'basaLoma': ['indit'],
      'basaLemesSorangan': ['mios'],
      'basaLemesBatur': ['angkat, jengkar'],
      'bahasaIndonesia': ['pergi'],
    },
    {
      'basaLoma': ['indung'],
      'basaLemesSorangan': ['(pun) biang'],
      'basaLemesBatur': ['(tuang) ibu'],
      'bahasaIndonesia': ['ibu'],
    },
    {
      'basaLoma': ['inget'],
      'basaLemesSorangan': ['émut'],
      'basaLemesBatur': ['émut'],
      'bahasaIndonesia': ['ingat'],
    },
    {
      'basaLoma': ['inggis'],
      'basaLemesSorangan': ['rémpan'],
      'basaLemesBatur': ['rémpan'],
      'bahasaIndonesia': ['takut'],
    },
    {
      'basaLoma': ['injeum'],
      'basaLemesSorangan': ['tambut'],
      'basaLemesBatur': ['tambut'],
      'bahasaIndonesia': ['pinjam'],
    },
    {
      'basaLoma': ['inum'],
      'basaLemesSorangan': ['leueut'],
      'basaLemesBatur': ['leuet'],
      'bahasaIndonesia': ['minum'],
    },
    {
      'basaLoma': ['irung'],
      'basaLemesSorangan': ['irung'],
      'basaLemesBatur': ['pangambung'],
      'bahasaIndonesia': ['hidung'],
    },
    {
      'basaLoma': ['isuk'],
      'basaLemesSorangan': ['énjing, énjing-énjing'],
      'basaLemesBatur': ['énjing, énjing-énjing'],
      'bahasaIndonesia': ['pagi'],
    },
    {
      'basaLoma': ['isukan'],
      'basaLemesSorangan': ['énjing'],
      'basaLemesBatur': ['énjing'],
      'bahasaIndonesia': ['besok'],
    },
    {
      'basaLoma': ['isuk-isuk'],
      'basaLemesSorangan': ['énjing, énjing-énjing'],
      'basaLemesBatur': ['énjing, énjing-énjing'],
      'bahasaIndonesia': ['pagi'],
    },
    {
      'basaLoma': ['iteuk'],
      'basaLemesSorangan': ['iteuk'],
      'basaLemesBatur': ['teteken'],
      'bahasaIndonesia': ['tongkat'],
    },
    {
      'basaLoma': ['itung'],
      'basaLemesSorangan': ['itung'],
      'basaLemesBatur': ['étang'],
      'bahasaIndonesia': ['menghitung'],
    },
    {
      'basaLoma': ['iwal'],
      'basaLemesSorangan': ['anging, (ka)jabi'],
      'basaLemesBatur': ['anging, (ka)jabi'],
      'bahasaIndonesia': ['kecuali'],
    },
    {
      'basaLoma': ['jaba'],
      'basaLemesSorangan': ['anging, (ka)jabi'],
      'basaLemesBatur': ['anging, (ka)jabi'],
      'bahasaIndonesia': ['luar'],
    },
    {
      'basaLoma': ['jadi'],
      'basaLemesSorangan': ['janten'],
      'basaLemesBatur': ['janten'],
      'bahasaIndonesia': ['jadi'],
    },
    {
      'basaLoma': ['jaga'],
      'basaLemesSorangan': ['jagi'],
      'basaLemesBatur': ['jagi'],
      'bahasaIndonesia': ['jaga'],
    },
    {
      'basaLoma': ['jajaka'],
      'basaLemesSorangan': ['nonoman'],
      'basaLemesBatur': ['nonoman'],
      'bahasaIndonesia': ['perjaka'],
    },
    {
      'basaLoma': ['jalma'],
      'basaLemesSorangan': ['jalmi'],
      'basaLemesBatur': ['jalmi'],
      'bahasaIndonesia': ['manusia'],
    },
    {
      'basaLoma': ['jang'],
      'basaLemesSorangan': ['kanggo'],
      'basaLemesBatur': ['haturan, kanggo'],
      'bahasaIndonesia': ['untuk'],
    },
    {
      'basaLoma': ['jauh'],
      'basaLemesSorangan': ['tebih'],
      'basaLemesBatur': ['tebih'],
      'bahasaIndonesia': ['jauh'],
    },
    {
      'basaLoma': ['jawab'],
      'basaLemesSorangan': ['walon'],
      'basaLemesBatur': ['waler'],
      'bahasaIndonesia': ['jawab'],
    },
    {
      'basaLoma': ['jelema'],
      'basaLemesSorangan': ['jalmi'],
      'basaLemesBatur': ['jalmi'],
      'bahasaIndonesia': ['manusia'],
    },
    {
      'basaLoma': ['jero'],
      'basaLemesSorangan': ['lebet'],
      'basaLemesBatur': ['lebet'],
      'bahasaIndonesia': ['dalam'],
    },
    {
      'basaLoma': ['jeung'],
      'basaLemesSorangan': ['miwah, sareng'],
      'basaLemesBatur': ['miwah, sareng'],
      'bahasaIndonesia': ['dan'],
    },
    {
      'basaLoma': ['jeungna deui'],
      'basaLemesSorangan': ['sareng deui'],
      'basaLemesBatur': ['sareng deui'],
      'bahasaIndonesia': ['bersama lagi'],
    },
    {
      'basaLoma': ['jieun'],
      'basaLemesSorangan': ['damel'],
      'basaLemesBatur': ['damel'],
      'bahasaIndonesia': ['membuat'],
    },
    {
      'basaLoma': ['jiga'],
      'basaLemesSorangan': ['sapertos'],
      'basaLemesBatur': ['sakarupi, sapertos, sarupi'],
      'bahasaIndonesia': ['seperti'],
    },
    {
      'basaLoma': ['jima'],
      'basaLemesSorangan': ['sapatemon'],
      'basaLemesBatur': ['sapatemon, saresmi'],
      'bahasaIndonesia': ['berhubungan intim'],
    },
    {
      'basaLoma': ['jinah'],
      'basaLemesSorangan': ['jinah'],
      'basaLemesBatur': ['ngalambang sari'],
      'bahasaIndonesia': ['zina'],
    },
    {
      'basaLoma': ['joré'],
      'basaLemesSorangan': ['goréng'],
      'basaLemesBatur': ['awon'],
      'bahasaIndonesia': ['jelek'],
    },
    {
      'basaLoma': ['jual'],
      'basaLemesSorangan': ['ical'],
      'basaLemesBatur': ['ical'],
      'bahasaIndonesia': ['jual'],
    },
    {
      'basaLoma': ['jugjug'],
      'basaLemesSorangan': ['bujeng'],
      'basaLemesBatur': ['bujeng'],
      'bahasaIndonesia': ['tiba-tiba'],
    },
    {
      'basaLoma': ['juru'],
      'basaLemesSorangan': ['lahir'],
      'basaLemesBatur': ['babar'],
      'bahasaIndonesia': ['melahirkan'],
    },
    {
      'basaLoma': ['jurung'],
      'basaLemesSorangan': ['jurung'],
      'basaLemesBatur': ['pirawang'],
      'bahasaIndonesia': ['memberitahu'],
    },
    {
      'basaLoma': ['maap'],
      'basaLemesSorangan': ['hapunten'],
      'basaLemesBatur': ['haksama, haksami, hapunten'],
      'bahasaIndonesia': ['maaf'],
    },
    {
      'basaLoma': ['maca'],
      'basaLemesSorangan': ['maca'],
      'basaLemesBatur': ['maos'],
      'bahasaIndonesia': ['baca'],
    },
    {
      'basaLoma': ['magahan'],
      'basaLemesSorangan': ['mapagahan'],
      'basaLemesBatur': ['miwejang, ngawurukan'],
      'bahasaIndonesia': ['menasehati'],
    },
    {
      'basaLoma': ['mahal'],
      'basaLemesSorangan': ['awis'],
      'basaLemesBatur': ['awis'],
      'bahasaIndonesia': ['mahal'],
    },
    {
      'basaLoma': ['mahi'],
      'basaLemesSorangan': ['cekap'],
      'basaLemesBatur': ['cekap'],
      'bahasaIndonesia': ['muat, cukup'],
    },
    {
      'basaLoma': ['maju'],
      'basaLemesSorangan': ['majeng'],
      'basaLemesBatur': ['majeng'],
      'bahasaIndonesia': ['maju'],
    },
    {
      'basaLoma': ['maké'],
      'basaLemesSorangan': ['nganggo'],
      'basaLemesBatur': ['nganggo'],
      'bahasaIndonesia': ['memakai'],
    },
    {
      'basaLoma': ['maksud'],
      'basaLemesSorangan': ['maksad'],
      'basaLemesBatur': ['maksad'],
      'bahasaIndonesia': ['maksud'],
    },
    {
      'basaLoma': ['malah'],
      'basaLemesSorangan': ['malih'],
      'basaLemesBatur': ['malih'],
      'bahasaIndonesia': ['malah'],
    },
    {
      'basaLoma': ['malahmandar'],
      'basaLemesSorangan': ['mamanawian'],
      'basaLemesBatur': ['mamanawian'],
      'bahasaIndonesia': ['mudah-mudahan'],
    },
    {
      'basaLoma': ['malarat'],
      'basaLemesSorangan': ['jalmi teu gaduh'],
      'basaLemesBatur': ['teu kagungan nanaon'],
      'bahasaIndonesia': ['miskin'],
    },
    {
      'basaLoma': ['malem'],
      'basaLemesSorangan': ['wengi'],
      'basaLemesBatur': ['wengi'],
      'bahasaIndonesia': ['malam'],
    },
    {
      'basaLoma': ['malik'],
      'basaLemesSorangan': ['malik'],
      'basaLemesBatur': ['mayun'],
      'bahasaIndonesia': ['menghadap, berbalik'],
    },
    {
      'basaLoma': ['maliré'],
      'basaLemesSorangan': ['maliré'],
      'basaLemesBatur': ['merhatoskeun'],
      'bahasaIndonesia': ['memperhatikan'],
    },
    {
      'basaLoma': ['mamayu'],
      'basaLemesSorangan': ['mamayu'],
      'basaLemesBatur': ['mamajeng'],
      'bahasaIndonesia': ['nafsu makan setelah sembuh'],
    },
    {
      'basaLoma': ['mandéan'],
      'basaLemesSorangan': ['mandéan'],
      'basaLemesBatur': ['mapadani, nyamian'],
      'bahasaIndonesia': ['menyamai'],
    },
    {
      'basaLoma': ['mandi'],
      'basaLemesSorangan': ['mandi'],
      'basaLemesBatur': ['siram, ngebak'],
      'bahasaIndonesia': ['mandi'],
    },
    {
      'basaLoma': ['manéh'],
      'basaLemesSorangan': ['-'],
      'basaLemesBatur': ['anjeun, salira'],
      'bahasaIndonesia': ['kamu'],
    },
    {
      'basaLoma': ['manéhna'],
      'basaLemesSorangan': ['-'],
      'basaLemesBatur': ['anjeunna'],
      'bahasaIndonesia': ['kamunya'],
    },
    {
      'basaLoma': ['manggih'],
      'basaLemesSorangan': ['mendak'],
      'basaLemesBatur': ['mendak'],
      'bahasaIndonesia': ['bertemu'],
    },
    {
      'basaLoma': ['mangka'],
      'basaLemesSorangan': ['mugi'],
      'basaLemesBatur': ['mugi(a)'],
      'bahasaIndonesia': ['semoga'],
    },
    {
      'basaLoma': ['mangku'],
      'basaLemesSorangan': ['mangku'],
      'basaLemesBatur': ['mangkon'],
      'bahasaIndonesia': ['memangku'],
    },
    {
      'basaLoma': ['mangkuk'],
      'basaLemesSorangan': ['kantos'],
      'basaLemesBatur': ['kantos'],
      'bahasaIndonesia': ['sudah, pernah'],
    },
    {
      'basaLoma': ['maot'],
      'basaLemesSorangan': ['nilar, tilar dunya, ngantunkeun'],
      'basaLemesBatur': ['pupus'],
      'bahasaIndonesia': ['meninggal'],
    },
    {
      'basaLoma': ['mapagahan'],
      'basaLemesSorangan': ['mapagahan'],
      'basaLemesBatur': ['miwejang, ngawurukan'],
      'bahasaIndonesia': ['menasehati'],
    },
    {
      'basaLoma': ['marak'],
      'basaLemesSorangan': ['marak'],
      'basaLemesBatur': ['munday'],
      'bahasaIndonesia': ['marak'],
    },
    {
      'basaLoma': ['marga'],
      'basaLemesSorangan': ['jalaran, (ku) margi'],
      'basaLemesBatur': ['(ku) margi, réh(ing)'],
      'bahasaIndonesia': ['dikira'],
    },
    {
      'basaLoma': ['marhum'],
      'basaLemesSorangan': ['jenatna, marhum'],
      'basaLemesBatur': ['marhum, suargi, suwargi'],
      'bahasaIndonesia': ['telah meninggal'],
    },
    {
      'basaLoma': ['mariksa'],
      'basaLemesSorangan': ['mariksa'],
      'basaLemesBatur': ['marios'],
      'bahasaIndonesia': ['memeriksa'],
    },
    {
      'basaLoma': ['marukanana'],
      'basaLemesSorangan': ['pangintenna'],
      'basaLemesBatur': ['pangintenna'],
      'bahasaIndonesia': ['kemungkinan'],
    },
    {
      'basaLoma': ['matuh'],
      'basaLemesSorangan': ['matuh'],
      'basaLemesBatur': ['linggih'],
      'bahasaIndonesia': ['patuh'],
    },
    {
      'basaLoma': ['mawa'],
      'basaLemesSorangan': ['ngabantun'],
      'basaLemesBatur': ['nyandak'],
      'bahasaIndonesia': ['bawa'],
    },
    {
      'basaLoma': ['mayit'],
      'basaLemesSorangan': ['layon'],
      'basaLemesBatur': ['layon'],
      'bahasaIndonesia': ['jenazah'],
    },
    {
      'basaLoma': ['mencak'],
      'basaLemesSorangan': ['nyobi'],
      'basaLemesBatur': ['nyobi'],
      'bahasaIndonesia': ['mencoba'],
    },
    {
      'basaLoma': ['megat'],
      'basaLemesSorangan': ['megat'],
      'basaLemesBatur': ['nyandeg'],
      'bahasaIndonesia': ['mencegat'],
    },
    {
      'basaLoma': ['melang'],
      'basaLemesSorangan': ['deudeupeun'],
      'basaLemesBatur': ['deudeupeun'],
      'bahasaIndonesia': ['khawatir'],
    },
    {
      'basaLoma': ['méméh'],
      'basaLemesSorangan': ['sateuacan'],
      'basaLemesBatur': ['sateuacan'],
      'bahasaIndonesia': ['sebelum'],
    },
    {
      'basaLoma': ['mencét'],
      'basaLemesSorangan': ['meuseul'],
      'basaLemesBatur': ['meuseul'],
      'bahasaIndonesia': ['pijat'],
    },
    {
      'basaLoma': ['mencétan'],
      'basaLemesSorangan': ['meuseulan'],
      'basaLemesBatur': ['meuseulan'],
      'bahasaIndonesia': ['memijat'],
    },
    {
      'basaLoma': ['mending'],
      'basaLemesSorangan': ['langkung saé'],
      'basaLemesBatur': ['langkung saé'],
      'bahasaIndonesia': ['lebih baik'],
    },
    {
      'basaLoma': ['menerkeun'],
      'basaLemesSorangan': ['ngalereskeun'],
      'basaLemesBatur': ['ngalereskeun'],
      'bahasaIndonesia': ['memperbaiki'],
    },
    {
      'basaLoma': ['mengi'],
      'basaLemesSorangan': ['asma'],
      'basaLemesBatur': ['ampeg'],
      'bahasaIndonesia': ['asma'],
    },
    {
      'basaLoma': ['ménta'],
      'basaLemesSorangan': ['neda, nyuhunkeun'],
      'basaLemesBatur': ['mundut'],
      'bahasaIndonesia': ['minta'],
    },
    {
      'basaLoma': ['méré'],
      'basaLemesSorangan': ['masihan'],
      'basaLemesBatur': ['maparin, ngahaturan(an), ngalélér'],
      'bahasaIndonesia': ['memberi'],
    },
    {
      'basaLoma': ['meujeuhna'],
      'basaLemesSorangan': ['cekap'],
      'basaLemesBatur': ['cekap'],
      'bahasaIndonesia': ['layak'],
    },
    {
      'basaLoma': ['meuli'],
      'basaLemesSorangan': ['mésér'],
      'basaLemesBatur': ['ngagaleuh'],
      'bahasaIndonesia': ['beli'],
    },
    {
      'basaLoma': ['meunang'],
      'basaLemesSorangan': ['kénging'],
      'basaLemesBatur': ['kénging'],
      'bahasaIndonesia': ['dapat'],
    },
    {
      'basaLoma': ['meureun'],
      'basaLemesSorangan': ['panginten'],
      'basaLemesBatur': ['panginten'],
      'bahasaIndonesia': ['barangkali'],
    },
    {
      'basaLoma': ['miang'],
      'basaLemesSorangan': ['mios'],
      'basaLemesBatur': ['angkat, jengkar'],
      'bahasaIndonesia': ['meminta izin'],
    },
    {
      'basaLoma': ['mihapé'],
      'basaLemesSorangan': ['ngawiat'],
      'basaLemesBatur': ['ngawewerat(an)'],
      'bahasaIndonesia': ['titip'],
    },
    {
      'basaLoma': ['mikeun'],
      'basaLemesSorangan': ['maparinkeun, masihkeun'],
      'basaLemesBatur': ['ngahaturkeun, nyanggakeun'],
      'bahasaIndonesia': ['memberikan'],
    },
    {
      'basaLoma': ['milang'],
      'basaLemesSorangan': ['ngétang'],
      'basaLemesBatur': ['ngétang'],
      'bahasaIndonesia': ['menghitung'],
    },
    {
      'basaLoma': ['milu'],
      'basaLemesSorangan': ['ngiring'],
      'basaLemesBatur': ['ngiring'],
      'bahasaIndonesia': ['ikut'],
    },
    {
      'basaLoma': ['mimiti'],
      'basaLemesSorangan': ['kawit'],
      'basaLemesBatur': ['awit, kawit'],
      'bahasaIndonesia': ['memulai'],
    },
    {
      'basaLoma': ['mimitina'],
      'basaLemesSorangan': ['kawitna'],
      'basaLemesBatur': ['awitna, kawitna'],
      'bahasaIndonesia': ['mulanya'],
    },
    {
      'basaLoma': ['minangka'],
      'basaLemesSorangan': ['étang-étang'],
      'basaLemesBatur': ['étang-étang'],
      'bahasaIndonesia': ['sebagai'],
    },
    {
      'basaLoma': ['minantu'],
      'basaLemesSorangan': ['minantu'],
      'basaLemesBatur': ['mantu'],
      'bahasaIndonesia': ['menantu'],
    },
    {
      'basaLoma': ['mindeng'],
      'basaLemesSorangan': ['sering'],
      'basaLemesBatur': ['sering'],
      'bahasaIndonesia': ['sering'],
    },
    {
      'basaLoma': ['minggat'],
      'basaLemesSorangan': ['minggat'],
      'basaLemesBatur': ['(nga)lolos'],
      'bahasaIndonesia': ['minggat'],
    },
    {
      'basaLoma': ['minyak'],
      'basaLemesSorangan': ['lisah'],
      'basaLemesBatur': ['lisah'],
      'bahasaIndonesia': ['minyak'],
    },
    {
      'basaLoma': ['mingeureuh'],
      'basaLemesSorangan': ['mingeureuh, ningal'],
      'basaLemesBatur': ['ningali'],
      'bahasaIndonesia': ['melihat'],
    },
    {
      'basaLoma': ['miskin'],
      'basaLemesSorangan': ['jalmi teu gaduh'],
      'basaLemesBatur': ['teu kagungan nanaon'],
      'bahasaIndonesia': ['miskin'],
    },
    {
      'basaLoma': ['mitoha'],
      'basaLemesSorangan': ['mitoha'],
      'basaLemesBatur': ['mertua'],
      'bahasaIndonesia': ['mertua'],
    },
    {
      'basaLoma': ['montok'],
      'basaLemesSorangan': ['montok'],
      'basaLemesBatur': ['ageung'],
      'bahasaIndonesia': ['gemuk'],
    },
    {
      'basaLoma': ['moro'],
      'basaLemesSorangan': ['moro'],
      'basaLemesBatur': ['bubujeng'],
      'bahasaIndonesia': ['mengejar, memburu'],
    },
    {
      'basaLoma': ['muga'],
      'basaLemesSorangan': ['mugi'],
      'basaLemesBatur': ['mugi(a)'],
      'bahasaIndonesia': ['semoga'],
    },
    {
      'basaLoma': ['muga-muga'],
      'basaLemesSorangan': ['mugi-mugi'],
      'basaLemesBatur': ['mugi-mugi'],
      'bahasaIndonesia': ['semoga'],
    },
    {
      'basaLoma': ['mulang'],
      'basaLemesSorangan': ['wangsul'],
      'basaLemesBatur': ['mulih'],
      'bahasaIndonesia': ['kembalian'],
    },
    {
      'basaLoma': ['mun'],
      'basaLemesSorangan': ['upami'],
      'basaLemesBatur': ['upami'],
      'bahasaIndonesia': ['kalau'],
    },
    {
      'basaLoma': ['mupakat'],
      'basaLemesSorangan': ['mupakat, rempug'],
      'basaLemesBatur': ['rempag'],
      'bahasaIndonesia': ['berunding, setuju'],
    },
    {
      'basaLoma': ['murah'],
      'basaLemesSorangan': ['mirah'],
      'basaLemesBatur': ['mirah'],
      'bahasaIndonesia': ['murah'],
    },
    {
      'basaLoma': ['muriang'],
      'basaLemesSorangan': ['muriang'],
      'basaLemesBatur': ['nyenyepan'],
      'bahasaIndonesia': ['meriang, panas dingin'],
    },
    {
      'basaLoma': ['muru'],
      'basaLemesSorangan': ['ngabujeng'],
      'basaLemesBatur': ['ngabujeng'],
      'bahasaIndonesia': ['mengejar'],
    },
    {
      'basaLoma': ['labuh'],
      'basaLemesSorangan': ['labuh'],
      'basaLemesBatur': ['geubis'],
      'bahasaIndonesia': ['jatuh'],
    },
    {
      'basaLoma': ['lahun'],
      'basaLemesSorangan': ['pangkon'],
      'basaLemesBatur': ['pangkon'],
      'bahasaIndonesia': ['pangku'],
    },
    {
      'basaLoma': ['lain'],
      'basaLemesSorangan': ['sanés'],
      'basaLemesBatur': ['sanés'],
      'bahasaIndonesia': ['bukan'],
    },
    {
      'basaLoma': ['laju'],
      'basaLemesSorangan': ['lajeng, teras'],
      'basaLemesBatur': ['lajeng, teras'],
      'bahasaIndonesia': ['terus-terusan'],
    },
    {
      'basaLoma': ['laki'],
      'basaLemesSorangan': ['lalaki'],
      'basaLemesBatur': ['pameget'],
      'bahasaIndonesia': ['laki-laki'],
    },
    {
      'basaLoma': ['laku'],
      'basaLemesSorangan': ['pajeng'],
      'basaLemesBatur': ['pajeng'],
      'bahasaIndonesia': ['laku'],
    },
    {
      'basaLoma': ['lalajo'],
      'basaLemesSorangan': ['nongton'],
      'basaLemesBatur': ['nongton'],
      'bahasaIndonesia': ['melihat, nonton'],
    },
    {
      'basaLoma': ['lalaki'],
      'basaLemesSorangan': ['lalaki'],
      'basaLemesBatur': ['pameget'],
      'bahasaIndonesia': ['lelaki'],
    },
    {
      'basaLoma': ['lamun'],
      'basaLemesSorangan': ['upami'],
      'basaLemesBatur': ['upami'],
      'bahasaIndonesia': ['kalau'],
    },
    {
      'basaLoma': ['lanceuk'],
      'basaLemesSorangan': ['(pun) lanceuk'],
      'basaLemesBatur': ['(tuang) raka'],
      'bahasaIndonesia': ['kakak'],
    },
    {
      'basaLoma': ['langka'],
      'basaLemesSorangan': ['awis, awis-awis'],
      'basaLemesBatur': ['awis, awis-awis'],
      'bahasaIndonesia': ['langka'],
    },
    {
      'basaLoma': ['lantaran'],
      'basaLemesSorangan': ['jalaran, (ku) margi'],
      'basaLemesBatur': ['(ku) margi, réh(ing)'],
      'bahasaIndonesia': ['sebab'],
    },
    {
      'basaLoma': ['lapar'],
      'basaLemesSorangan': ['hoyong neda, lapar'],
      'basaLemesBatur': ['palay tuang'],
      'bahasaIndonesia': ['lapar'],
    },
    {
      'basaLoma': ['laris'],
      'basaLemesSorangan': ['pajeng'],
      'basaLemesBatur': ['pajeng'],
      'bahasaIndonesia': ['laris'],
    },
    {
      'basaLoma': ['larung'],
      'basaLemesSorangan': ['langkung'],
      'basaLemesBatur': ['langkung'],
      'bahasaIndonesia': ['terlewati'],
    },
    {
      'basaLoma': ['laun'],
      'basaLemesSorangan': ['lami'],
      'basaLemesBatur': ['lami'],
      'bahasaIndonesia': ['lambat'],
    },
    {
      'basaLoma': ['laun-laun'],
      'basaLemesSorangan': ['lami-lami'],
      'basaLemesBatur': ['lami-lami'],
      'bahasaIndonesia': ['lambat laun'],
    },
    {
      'basaLoma': ['lawas'],
      'basaLemesSorangan': ['lami'],
      'basaLemesBatur': ['lami'],
      'bahasaIndonesia': ['lama'],
    },
    {
      'basaLoma': ['lebah'],
      'basaLemesSorangan': ['leresan'],
      'basaLemesBatur': ['leresan'],
      'bahasaIndonesia': ['sebelah, samping'],
    },
    {
      'basaLoma': ['lebaran'],
      'basaLemesSorangan': ['boboran (siam)'],
      'basaLemesBatur': ['boboran (siam)'],
      'bahasaIndonesia': ['lebaran'],
    },
    {
      'basaLoma': ['lého'],
      'basaLemesSorangan': ['umbel'],
      'basaLemesBatur': ['umbel'],
      'bahasaIndonesia': ['ingus'],
    },
    {
      'basaLoma': ['léngoh'],
      'basaLemesSorangan': ['léngoh, teu ngabantun nanaon'],
      'basaLemesBatur': ['teu nyandak nanaon'],
      'bahasaIndonesia': ['tidak membawa apa-apa'],
    },
    {
      'basaLoma': ['létah'],
      'basaLemesSorangan': ['létah'],
      'basaLemesBatur': ['ilat'],
      'bahasaIndonesia': ['lidah'],
    },
    {
      'basaLoma': ['létak'],
      'basaLemesSorangan': ['létak'],
      'basaLemesBatur': ['ilat'],
      'bahasaIndonesia': ['jilat'],
    },
    {
      'basaLoma': ['leumpang'],
      'basaLemesSorangan': ['leumpang'],
      'basaLemesBatur': ['angkat'],
      'bahasaIndonesia': ['jalan kaki, berangkat'],
    },
    {
      'basaLoma': ['leungeun'],
      'basaLemesSorangan': ['leungeun'],
      'basaLemesBatur': ['panangan'],
      'bahasaIndonesia': ['tangan'],
    },
    {
      'basaLoma': ['leungit'],
      'basaLemesSorangan': ['leungi'],
      'basaLemesBatur': ['ical'],
      'bahasaIndonesia': ['hilang'],
    },
    {
      'basaLoma': ['leutik'],
      'basaLemesSorangan': ['alit'],
      'basaLemesBatur': ['alit'],
      'bahasaIndonesia': ['kecil'],
    },
    {
      'basaLoma': ['leuwih'],
      'basaLemesSorangan': ['langkung'],
      'basaLemesBatur': ['langkung'],
      'bahasaIndonesia': ['lebih'],
    },
    {
      'basaLoma': ['leuwih hadé'],
      'basaLemesSorangan': ['langkung saé'],
      'basaLemesBatur': ['langkung saé'],
      'bahasaIndonesia': ['lebih baik'],
    },
    {
      'basaLoma': ['lila'],
      'basaLemesSorangan': ['lami'],
      'basaLemesBatur': ['lami'],
      'bahasaIndonesia': ['lama'],
    },
    {
      'basaLoma': ['liwat'],
      'basaLemesSorangan': ['langkung'],
      'basaLemesBatur': ['langkung'],
      'bahasaIndonesia': ['lewat'],
    },
    {
      'basaLoma': ['loba'],
      'basaLemesSorangan': ['seueur'],
      'basaLemesBatur': ['seueur'],
      'bahasaIndonesia': ['banyak'],
    },
    {
      'basaLoma': ['luput'],
      'basaLemesSorangan': ['lepat'],
      'basaLemesBatur': ['lepat'],
      'bahasaIndonesia': ['luput'],
    },
    {
      'basaLoma': ['kabar'],
      'basaLemesSorangan': ['wartos'],
      'basaLemesBatur': ['wartos'],
      'bahasaIndonesia': ['kabar'],
    },
    {
      'basaLoma': ['kabéh'],
      'basaLemesSorangan': ['sadaya'],
      'basaLemesBatur': ['sadaya'],
      'bahasaIndonesia': ['semua'],
    },
    {
      'basaLoma': ['kabéhanana'],
      'basaLemesSorangan': ['sadayana'],
      'basaLemesBatur': ['sadayana'],
      'bahasaIndonesia': ['semuanya'],
    },
    {
      'basaLoma': ['kabur'],
      'basaLemesSorangan': ['minggat'],
      'basaLemesBatur': ['(nga)lolos'],
      'bahasaIndonesia': ['kabur'],
    },
    {
      'basaLoma': ['kaburu'],
      'basaLemesSorangan': ['kabujeng'],
      'basaLemesBatur': ['kabujeng'],
      'bahasaIndonesia': ['terlanjur'],
    },
    {
      'basaLoma': ['kacamata'],
      'basaLemesSorangan': ['kacasoca'],
      'basaLemesBatur': ['kacasoca'],
      'bahasaIndonesia': ['kacamata'],
    },
    {
      'basaLoma': ['kacaritakeun'],
      'basaLemesSorangan': ['kacaritakeun'],
      'basaLemesBatur': ['kacaritakeun'],
      'bahasaIndonesia': ['diceritakan'],
    },
    {
      'basaLoma': ['kacida'],
      'basaLemesSorangan': ['kalintang'],
      'basaLemesBatur': ['kalintang, teu kinten'],
      'bahasaIndonesia': ['sangat'],
    },
    {
      'basaLoma': ['kaciri'],
      'basaLemesSorangan': ['katawis'],
      'basaLemesBatur': ['katawis'],
      'bahasaIndonesia': ['dikenali'],
    },
    {
      'basaLoma': ['kadang'],
      'basaLemesSorangan': ['wargi'],
      'basaLemesBatur': ['wargi'],
      'bahasaIndonesia': ['saudara'],
    },
    {
      'basaLoma': ['kadang warga'],
      'basaLemesSorangan': ['kadang wargi'],
      'basaLemesBatur': ['wargi-wargi sadayana'],
      'bahasaIndonesia': ['saudara sekalian'],
    },
    {
      'basaLoma': ['kadé'],
      'basaLemesSorangan': ['ati-ati'],
      'basaLemesBatur': ['atos-atos'],
      'bahasaIndonesia': ['hati-hati'],
    },
    {
      'basaLoma': ['kadudukan'],
      'basaLemesSorangan': ['kadudukan'],
      'basaLemesBatur': ['kalungguhan'],
      'bahasaIndonesia': ['kedudukan'],
    },
    {
      'basaLoma': ['kagegeringan'],
      'basaLemesSorangan': ['kaleleban'],
      'basaLemesBatur': ['kaleleban'],
      'bahasaIndonesia': ['sakit'],
    },
    {
      'basaLoma': ['kagok'],
      'basaLemesSorangan': ['(ka)pambeng'],
      'basaLemesBatur': ['(ka)pambeng'],
      'bahasaIndonesia': ['tanggung'],
    },
    {
      'basaLoma': ['kajaba'],
      'basaLemesSorangan': ['kajabi'],
      'basaLemesBatur': ['kajabi'],
      'bahasaIndonesia': ['kecuali'],
    },
    {
      'basaLoma': ['kajeun'],
      'basaLemesSorangan': ['sawios, teu sawios, wios'],
      'basaLemesBatur': ['sawios, teu sawios, wios'],
      'bahasaIndonesia': ['biarkan'],
    },
    {
      'basaLoma': ['kakara'],
      'basaLemesSorangan': ['nembé'],
      'basaLemesBatur': ['nembé'],
      'bahasaIndonesia': ['baru saja'],
    },
    {
      'basaLoma': ['kakus'],
      'basaLemesSorangan': ['jamban'],
      'basaLemesBatur': ['jamban'],
      'bahasaIndonesia': ['jamban, toilet'],
    },
    {
      'basaLoma': ['kalan-kalan'],
      'basaLemesSorangan': ['sawaktos-waktos'],
      'basaLemesBatur': ['sawaktos-waktos'],
      'bahasaIndonesia': ['sewaktu-waktu'],
    },
    {
      'basaLoma': ['kalarung'],
      'basaLemesSorangan': ['kalangkung'],
      'basaLemesBatur': ['kalangkung'],
      'bahasaIndonesia': ['terlewat'],
    },
    {
      'basaLoma': ['kalenger'],
      'basaLemesSorangan': ['kapiuhan'],
      'basaLemesBatur': ['kapidara'],
      'bahasaIndonesia': ['pingsan'],
    },
    {
      'basaLoma': ['kamar'],
      'basaLemesSorangan': ['pamondokan'],
      'basaLemesBatur': ['pajuruan, pangkuleman'],
      'bahasaIndonesia': ['kamar'],
    },
    {
      'basaLoma': ['kamar mandi'],
      'basaLemesSorangan': ['jamban'],
      'basaLemesBatur': ['jamban'],
      'bahasaIndonesia': ['jamban, toilet'],
    },
    {
      'basaLoma': ['kanyeri'],
      'basaLemesSorangan': ['kanyeri'],
      'basaLemesBatur': ['kasawat'],
      'bahasaIndonesia': ['sakit'],
    },
    {
      'basaLoma': ['kapaéhan'],
      'basaLemesSorangan': ['kapiuhan'],
      'basaLemesBatur': ['kapidara'],
      'bahasaIndonesia': ['pingsan'],
    },
    {
      'basaLoma': ['kapalang'],
      'basaLemesSorangan': ['(ka)pambeng'],
      'basaLemesBatur': ['(ka)pambeng'],
      'bahasaIndonesia': ['tanggung'],
    },
    {
      'basaLoma': ['kapegat'],
      'basaLemesSorangan': ['kapegat'],
      'basaLemesBatur': ['kaandeg'],
      'bahasaIndonesia': ['tercegat'],
    },
    {
      'basaLoma': ['kapilih'],
      'basaLemesSorangan': ['kapeto'],
      'basaLemesBatur': ['kaselir'],
      'bahasaIndonesia': ['terpilih'],
    },
    {
      'basaLoma': ['karasa'],
      'basaLemesSorangan': ['karaos'],
      'basaLemesBatur': ['karaos'],
      'bahasaIndonesia': ['terasa'],
    },
    {
      'basaLoma': ['karék'],
      'basaLemesSorangan': ['nembé'],
      'basaLemesBatur': ['nembé'],
      'bahasaIndonesia': ['baru saja'],
    },
    {
      'basaLoma': ['karémbong'],
      'basaLemesSorangan': ['karémbong'],
      'basaLemesBatur': ['kekemben'],
      'bahasaIndonesia': ['selempang'],
    },
    {
      'basaLoma': ['karesep'],
      'basaLemesSorangan': ['karesep'],
      'basaLemesBatur': ['kalangen, kaseneng, kasedep'],
      'bahasaIndonesia': ['yang disukai, hobi'],
    },
    {
      'basaLoma': ['kari'],
      'basaLemesSorangan': ['kantun'],
      'basaLemesBatur': ['kantun'],
      'bahasaIndonesia': ['sisa'],
    },
    {
      'basaLoma': ['karunya'],
      'basaLemesSorangan': ['hawatos'],
      'basaLemesBatur': ['hawatos'],
      'bahasaIndonesia': ['kasihan'],
    },
    {
      'basaLoma': ['kasakit'],
      'basaLemesSorangan': ['kasakit'],
      'basaLemesBatur': ['kasawat'],
      'bahasaIndonesia': ['sakit'],
    },
    {
      'basaLoma': ['kasanding'],
      'basaLemesSorangan': ['kasanding'],
      'basaLemesBatur': ['kasumpingan'],
      'bahasaIndonesia': ['kedatangan'],
    },
    {
      'basaLoma': ['kasurupan'],
      'basaLemesSorangan': ['kasarumahan'],
      'basaLemesBatur': ['kacalikan'],
      'bahasaIndonesia': ['kesurupan'],
    },
    {
      'basaLoma': ['katangén'],
      'basaLemesSorangan': ['katangén'],
      'basaLemesBatur': ['kauninga'],
      'bahasaIndonesia': ['ketahuan'],
    },
    {
      'basaLoma': ['katara'],
      'basaLemesSorangan': ['katawis'],
      'basaLemesBatur': ['katawis'],
      'bahasaIndonesia': ['terlihat'],
    },
    {
      'basaLoma': ['katuhu'],
      'basaLemesSorangan': ['katuhu'],
      'basaLemesBatur': ['tengen'],
      'bahasaIndonesia': ['kanan'],
    },
    {
      'basaLoma': ['kawantu'],
      'basaLemesSorangan': ['kawantos'],
      'basaLemesBatur': ['kawantos'],
      'bahasaIndonesia': ['keberanian'],
    },
    {
      'basaLoma': ['kawas'],
      'basaLemesSorangan': ['sapertos'],
      'basaLemesBatur': ['sakarupi, sapertos, sarupi'],
      'bahasaIndonesia': ['seperti'],
    },
    {
      'basaLoma': ['kawilang'],
      'basaLemesSorangan': ['kaétang'],
      'basaLemesBatur': ['kaétang'],
      'bahasaIndonesia': ['kehitung'],
    },
    {
      'basaLoma': ['kawin'],
      'basaLemesSorangan': ['jatukrami, ngadahup, nikah, réndéngan'],
      'basaLemesBatur': ['jatukrami, ngadahup, nikah, réndéngan'],
      'bahasaIndonesia': ['nikah'],
    },
    {
      'basaLoma': ['kédé'],
      'basaLemesSorangan': ['kénca'],
      'basaLemesBatur': ['kiwa'],
      'bahasaIndonesia': ['kiri'],
    },
    {
      'basaLoma': ['kedeng'],
      'basaLemesSorangan': ['kedeng'],
      'basaLemesBatur': ['ébog'],
      'bahasaIndonesia': ['berbaring'],
    },
    {
      'basaLoma': ['kéjo'],
      'basaLemesSorangan': ['sangu'],
      'basaLemesBatur': ['sangu'],
      'bahasaIndonesia': ['nasi'],
    },
    {
      'basaLoma': ['kélék'],
      'basaLemesSorangan': ['kélék'],
      'basaLemesBatur': ['déhé, ingkab'],
      'bahasaIndonesia': ['ketiak'],
    },
    {
      'basaLoma': ['kénca'],
      'basaLemesSorangan': ['kénca'],
      'basaLemesBatur': ['kiwa'],
      'bahasaIndonesia': ['kiri'],
    },
    {
      'basaLoma': ['keris'],
      'basaLemesSorangan': ['duhung'],
      'basaLemesBatur': ['duhung'],
      'bahasaIndonesia': ['keris'],
    },
    {
      'basaLoma': ['késang'],
      'basaLemesSorangan': ['késang'],
      'basaLemesBatur': ['karinget'],
      'bahasaIndonesia': ['keringat'],
    },
    {
      'basaLoma': ['keun baé'],
      'basaLemesSorangan': ['sawios, teu sawios, wios'],
      'basaLemesBatur': ['sawios, teu sawios, wios'],
      'bahasaIndonesia': ['biarkan saja'],
    },
    {
      'basaLoma': ['keur'],
      'basaLemesSorangan': ['nuju'],
      'basaLemesBatur': ['nuju'],
      'bahasaIndonesia': ['sedang'],
    },
    {
      'basaLoma': ['keur (pikeun)'],
      'basaLemesSorangan': ['kanggo'],
      'basaLemesBatur': ['haturan, kanggo'],
      'bahasaIndonesia': ['untuk'],
    },
    {
      'basaLoma': ['kiih'],
      'basaLemesSorangan': ['kahampangan'],
      'basaLemesBatur': ['kahampangan'],
      'bahasaIndonesia': ['kencing'],
    },
    {
      'basaLoma': ['kira'],
      'basaLemesSorangan': ['kinten'],
      'basaLemesBatur': ['kinten'],
      'bahasaIndonesia': ['mengira'],
    },
    {
      'basaLoma': ['kira-kira'],
      'basaLemesSorangan': ['kinten-kinten'],
      'basaLemesBatur': ['kinten-kinten'],
      'bahasaIndonesia': ['kira-kira'],
    },
    {
      'basaLoma': ['kirim'],
      'basaLemesSorangan': ['kintun'],
      'basaLemesBatur': ['kintun'],
      'bahasaIndonesia': ['kirim'],
    },
    {
      'basaLoma': ['kocap'],
      'basaLemesSorangan': ['kacaritakeun'],
      'basaLemesBatur': ['kacaritakeun'],
      'bahasaIndonesia': ['terceritakan'],
    },
    {
      'basaLoma': ['kocapkeun'],
      'basaLemesSorangan': ['kacaritakeun'],
      'basaLemesBatur': ['kacaritakeun'],
      'bahasaIndonesia': ['terceritakan'],
    },
    {
      'basaLoma': ['kolot'],
      'basaLemesSorangan': ['kolot'],
      'basaLemesBatur': ['sepuh'],
      'bahasaIndonesia': ['tua'],
    },
    {
      'basaLoma': ['komo'],
      'basaLemesSorangan': ['sumawonten'],
      'basaLemesBatur': ['sumawonten'],
      'bahasaIndonesia': ['bahkan'],
    },
    {
      'basaLoma': ['kongkorong'],
      'basaLemesSorangan': ['kongkorong'],
      'basaLemesBatur': ['kangkalung'],
      'bahasaIndonesia': ['kalung'],
    },
    {
      'basaLoma': ['kop'],
      'basaLemesSorangan': ['mangga'],
      'basaLemesBatur': ['mangga'],
      'bahasaIndonesia': ['silakan'],
    },
    {
      'basaLoma': ['kotoran'],
      'basaLemesSorangan': ['kareseban, udur sasih'],
      'basaLemesBatur': ['kareseban'],
      'bahasaIndonesia': ['haid'],
    },
    {
      'basaLoma': ['kuat'],
      'basaLemesSorangan': ['kiat'],
      'basaLemesBatur': ['kiat'],
      'bahasaIndonesia': ['kuat'],
    },
    {
      'basaLoma': ['kubur'],
      'basaLemesSorangan': ['kaluat'],
      'basaLemesBatur': ['kureb'],
      'bahasaIndonesia': ['mengubur'],
    },
    {
      'basaLoma': ['kudu'],
      'basaLemesSorangan': ['kedah'],
      'basaLemesBatur': ['kedah'],
      'bahasaIndonesia': ['harus'],
    },
    {
      'basaLoma': ['kuku'],
      'basaLemesSorangan': ['kuku'],
      'basaLemesBatur': ['tanggay'],
      'bahasaIndonesia': ['kuku'],
    },
    {
      'basaLoma': ['kukumbah'],
      'basaLemesSorangan': ['wawasuh'],
      'basaLemesBatur': ['wawasuh'],
      'bahasaIndonesia': ['mencuci'],
    },
    {
      'basaLoma': ['kulawarga'],
      'basaLemesSorangan': ['kulawargi'],
      'basaLemesBatur': ['kulawargi'],
      'bahasaIndonesia': ['saudara sekalian'],
    },
    {
      'basaLoma': ['kuluwut'],
      'basaLemesSorangan': ['nguluwut, nguyung'],
      'basaLemesBatur': ['ngangluh'],
      'bahasaIndonesia': ['murung'],
    },
    {
      'basaLoma': ['kumbah'],
      'basaLemesSorangan': ['wasuh'],
      'basaLemesBatur': ['wasuh'],
      'bahasaIndonesia': ['mencuci'],
    },
    {
      'basaLoma': ['kumis'],
      'basaLemesSorangan': ['kumis'],
      'basaLemesBatur': ['rumbah'],
      'bahasaIndonesia': ['kumis'],
    },
    {
      'basaLoma': ['kumpul'],
      'basaLemesSorangan': ['kempel'],
      'basaLemesBatur': ['kempel'],
      'bahasaIndonesia': ['kumpul'],
    },
    {
      'basaLoma': ['kungsi'],
      'basaLemesSorangan': ['kantos'],
      'basaLemesBatur': ['kantos'],
      'bahasaIndonesia': ['pernah'],
    },
    {
      'basaLoma': ['kurang'],
      'basaLemesSorangan': ['kirang'],
      'basaLemesBatur': ['kirang'],
      'bahasaIndonesia': ['kurang'],
    },
    {
      'basaLoma': ['kuren'],
      'basaLemesSorangan': ['rimbit'],
      'basaLemesBatur': ['rimbit'],
      'bahasaIndonesia': ['berkeluarga'],
    },
    {
      'basaLoma': ['kurenan'],
      'basaLemesSorangan': ['rimbitan'],
      'basaLemesBatur': ['rimbitan'],
      'bahasaIndonesia': ['kekeluargaan'],
    },
    {
      'basaLoma': ['kuring'],
      'basaLemesSorangan': ['abdi, sim kuring'],
      'basaLemesBatur': ['-'],
      'bahasaIndonesia': ['saya'],
    },
    {
      'basaLoma': ['kurung saréréa'],
      'basaLemesSorangan': ['abdi sadayana'],
      'basaLemesBatur': ['-'],
      'bahasaIndonesia': ['kita semua'],
    },
    {
      'basaLoma': ['kuru'],
      'basaLemesSorangan': ['begang'],
      'basaLemesBatur': ['langsip, langsit'],
      'bahasaIndonesia': ['kurus'],
    },
    {
      'basaLoma': ['kutu'],
      'basaLemesSorangan': ['kutu'],
      'basaLemesBatur': ['puntang'],
      'bahasaIndonesia': ['kutu'],
    },
  ];
}
